/* PART 3 · 질문에 답하기 (Q5·Q6 15초 / Q7 30초)
   Q5·Q6 조각: a(답) · why(이유) · ex(예시)      → "a. That's because why. For example, ex."
   Q7 조각:    a(의견) · r1 · r2(이유) · ex(예시) → "a. I have two reasons. First, r1. For example, ex. Second, r2. That's why I think so." */
const I3 = (topic, who) => `Imagine that ${who} is doing research in your area. You have agreed to participate in a telephone interview about ${topic}.`;
BANK.part3 = [
  { id: 'p3-01', topic: '여가 · 영화', intro: I3('going to the movies', 'a movie theater company'), questions: [
    { q: 'How often do you go to the movies, and who do you usually go with?', a: 'I go to the movies about once a month with my friends', why: 'it is a fun way to relieve stress', ex: 'last weekend, we watched an action movie together' },
    { q: 'Do you prefer to watch movies at a theater or at home? Why?', a: 'I prefer to watch movies at a theater', why: 'the screen is big and the sound is great', ex: 'I can focus on the movie without my phone' },
    { q: 'What factors do you consider when choosing a movie to watch? Why?', a: 'I think reviews and the genre are the most important', r1: 'I always check online reviews, because I don\'t want to waste my time and money', r2: 'I like action movies, because they help me relieve stress', ex: 'last month, I chose a movie with great reviews, and it was really fun' } ] },
  { id: 'p3-02', topic: '쇼핑 · 옷', intro: I3('shopping for clothes', 'a clothing company'), questions: [
    { q: 'When was the last time you bought clothes, and what did you buy?', a: 'The last time I bought clothes was last month, and I bought a warm jacket', why: 'the weather suddenly got cold', ex: 'I bought it at a shopping mall near my house' },
    { q: 'Do you usually shop for clothes online or at a store? Why?', a: 'I usually shop for clothes online', why: 'it is convenient and it saves time', ex: 'I can compare prices easily at home' },
    { q: 'If a new clothing store opened in your area, what would make you want to visit it? Why?', a: 'I would visit the store if it had a big sale', r1: 'I am a student, so I want to save money', r2: 'I would visit if it had unique styles that I can\'t find online', ex: 'last year, a new store near my house had a thirty percent sale, and I bought two shirts' } ] },
  { id: 'p3-03', topic: '교통 · 대중교통', intro: I3('public transportation', 'a city transportation department'), questions: [
    { q: 'How do you usually get to work or school, and how long does it take?', a: 'I usually take the subway to work, and it takes about thirty minutes', why: 'the subway is fast and cheap', ex: 'I listen to music on the way' },
    { q: 'Is public transportation in your area convenient? Why or why not?', a: 'Yes, public transportation in my area is very convenient', why: 'there is a subway station near my house', ex: 'buses come every ten minutes, so I don\'t have to wait long' },
    { q: 'What improvements would you suggest for public transportation in your city? Why?', a: 'I think the city should add more buses in the morning', r1: 'buses are too crowded during rush hour, so it is very stressful', r2: 'the subway should run later at night, because many people work late', ex: 'last week, I missed the last train and had to take an expensive taxi' } ] },
  { id: 'p3-04', topic: '음식 · 외식', intro: I3('eating out', 'a restaurant association'), questions: [
    { q: 'How often do you eat out, and who do you usually eat with?', a: 'I eat out about twice a week with my coworkers', why: 'I am too busy to cook at home', ex: 'we usually have lunch near our office' },
    { q: 'What kind of food do you usually eat when you eat out? Why?', a: 'I usually eat Korean food like bibimbap', why: 'it is healthy and delicious', ex: 'it has a lot of vegetables' },
    { q: 'When choosing a restaurant, what is the most important factor: price, taste, or location? Why?', a: 'I think taste is the most important factor', r1: 'if the food is not delicious, I don\'t want to go there again', r2: 'good food makes me happy and relieves my stress', ex: 'there is a small restaurant near my house, and I go there every week because the food is great' } ] },
  { id: 'p3-05', topic: '운동 · 건강', intro: I3('exercise', 'a fitness magazine'), questions: [
    { q: 'How often do you exercise, and what kind of exercise do you do?', a: 'I exercise about three times a week, and I usually go jogging', why: 'it is easy and I can do it anytime', ex: 'I jog in the park near my house' },
    { q: 'Do you prefer to exercise alone or with other people? Why?', a: 'I prefer to exercise alone', why: 'I can exercise at my own pace', ex: 'I can listen to my favorite music while I run' },
    { q: 'Would you be interested in joining a fitness class at a community center? Why or why not?', a: 'Yes, I would be interested in joining a fitness class', r1: 'a trainer can teach me the right way to exercise', r2: 'I can meet new people and stay motivated', ex: 'last year, I took a yoga class, and it really helped me stay healthy' } ] },
  { id: 'p3-06', topic: '음악', intro: I3('music', 'a music company'), questions: [
    { q: 'When do you usually listen to music, and how do you listen to it?', a: 'I usually listen to music on my way to work with my smartphone', why: 'it makes my commute more enjoyable', ex: 'I use a music app every day' },
    { q: 'Have you ever been to a concert? Tell me about it.', a: 'Yes, I went to a concert last year', why: 'my favorite singer had a concert in Seoul', ex: 'it was really exciting to sing along with other fans' },
    { q: 'Do you think it is a good idea to learn to play a musical instrument? Why or why not?', a: 'Yes, I think it is a good idea to learn to play an instrument', r1: 'playing music is a great way to relieve stress', r2: 'it helps people become more patient and focused', ex: 'I learned the guitar last year, and now I play it when I feel stressed' } ] },
  { id: 'p3-07', topic: '스마트폰 · 전자기기', intro: I3('smartphones', 'an electronics company'), questions: [
    { q: 'How many hours a day do you use your smartphone, and what do you mainly use it for?', a: 'I use my smartphone about four hours a day, mainly for messaging and watching videos', why: 'it is the easiest way to contact my friends', ex: 'I also check the news on it every morning' },
    { q: 'When was the last time you bought a new phone? Why did you buy it?', a: 'The last time I bought a new phone was two years ago', why: 'my old phone was too slow', ex: 'the battery also died very quickly' },
    { q: 'What is the most important thing to consider when buying a smartphone? Why?', a: 'I think the battery life is the most important thing', r1: 'I use my phone all day, so a long battery life is very convenient', r2: 'I don\'t want to carry a charger everywhere', ex: 'my old phone died in the middle of the day, so I missed an important call' } ] },
  { id: 'p3-08', topic: '독서 · 책', intro: I3('reading books', 'a publishing company'), questions: [
    { q: 'How often do you read books, and what kind of books do you read?', a: 'I read a book about once a month, and I usually read novels', why: 'novels are interesting and help me relax', ex: 'I usually read before going to bed' },
    { q: 'Do you prefer reading paper books or e-books? Why?', a: 'I prefer reading e-books', why: 'I can read them anytime and anywhere on my phone', ex: 'I often read on the subway' },
    { q: 'Do you think people read fewer books these days than in the past? Why?', a: 'Yes, I think people read fewer books these days', r1: 'people spend a lot of time on their smartphones', r2: 'people are too busy with work and study', ex: 'on the subway, most people watch videos instead of reading books' } ] },
  { id: 'p3-09', topic: '여행', intro: I3('traveling', 'a travel agency'), questions: [
    { q: 'When was the last time you went on a trip, and where did you go?', a: 'The last time I went on a trip was last summer, and I went to Jeju Island', why: 'I wanted to relax by the beach', ex: 'I went there with my family for three days' },
    { q: 'Do you prefer to travel alone or with others? Why?', a: 'I prefer to travel with my friends', why: 'we can share good memories and split the costs', ex: 'it is also safer to travel together' },
    { q: 'What do you think is the best way to find information about a travel destination? Why?', a: 'I think the internet is the best way to find travel information', r1: 'I can find a lot of information quickly and for free', r2: 'I can read real reviews from other travelers', ex: 'before my trip to Jeju, I found a great restaurant from a blog review' } ] },
  { id: 'p3-10', topic: '카페 · 커피숍', intro: I3('coffee shops', 'a coffee company'), questions: [
    { q: 'How often do you go to a coffee shop, and what do you usually order?', a: 'I go to a coffee shop almost every day, and I usually order an iced americano', why: 'coffee helps me wake up in the morning', ex: 'I buy one on my way to work' },
    { q: 'Do you ever study or work at a coffee shop? Why or why not?', a: 'Yes, I often study at a coffee shop', why: 'I can focus better than at home', ex: 'the background music helps me concentrate' },
    { q: 'If a new coffee shop opened in your neighborhood, what would make you go there? Why?', a: 'I would go there if it had a comfortable place to study', r1: 'I often study at coffee shops, so I need a quiet and comfortable space', r2: 'I would go if the coffee was cheap, because I drink coffee every day', ex: 'my favorite coffee shop has big tables and free Wi-Fi, so I go there every weekend' } ] },
  { id: 'p3-11', topic: '동네 · 이웃', intro: I3('your neighborhood', 'a real estate company'), questions: [
    { q: 'How long have you lived in your neighborhood, and do you like it?', a: 'I have lived in my neighborhood for five years, and I really like it', why: 'it is quiet and safe', ex: 'there is also a big park nearby' },
    { q: 'What do you like the most about your neighborhood? Why?', a: 'I like the convenient location the most', why: 'there are many stores and restaurants near my house', ex: 'the subway station is only five minutes away' },
    { q: 'What facility would you like to have in your neighborhood? Why?', a: 'I would like to have a big library in my neighborhood', r1: 'I could study there for free without spending money at coffee shops', r2: 'it would be a great place for children and students', ex: 'right now, I have to take a bus for thirty minutes to go to the library' } ] },
  { id: 'p3-12', topic: '공원 · 야외 활동', intro: I3('parks', 'a city parks department'), questions: [
    { q: 'How often do you go to a park, and what do you usually do there?', a: 'I go to a park about twice a week, and I usually take a walk', why: 'walking helps me relieve stress', ex: 'I often go there after dinner' },
    { q: 'Who do you usually go to the park with? Why?', a: 'I usually go to the park with my dog', why: 'my dog loves to run on the grass', ex: 'we play together for about an hour' },
    { q: 'What would make you visit parks more often? Why?', a: 'I would visit parks more often if there were more events', r1: 'events like outdoor concerts are fun and free', r2: 'more benches and shade would make the park more comfortable', ex: 'last summer, there was a movie night in the park, and I really enjoyed it with my friends' } ] },
  { id: 'p3-13', topic: '온라인 쇼핑', intro: I3('online shopping', 'a marketing firm'), questions: [
    { q: 'What was the last thing you bought online, and how long did it take to arrive?', a: 'The last thing I bought online was a pair of sneakers, and it took two days to arrive', why: 'delivery is very fast in my country', ex: 'I ordered them on my phone at night' },
    { q: 'What kinds of products do you usually buy online? Why?', a: 'I usually buy clothes and daily supplies online', why: 'they are cheaper online than in stores', ex: 'there are many discounts and coupons' },
    { q: 'What are the disadvantages of shopping online? Explain.', a: 'I think there are two main disadvantages of shopping online', r1: 'I can\'t see or touch the product before I buy it', r2: 'returning a product can take a lot of time', ex: 'last month, I bought a shirt online, but it was too small, so I had to send it back' } ] },
  { id: 'p3-14', topic: '선물', intro: I3('buying gifts', 'a gift shop'), questions: [
    { q: 'When was the last time you bought a gift, and who was it for?', a: 'The last time I bought a gift was last week, and it was for my mother', why: 'it was her birthday', ex: 'I bought her a nice scarf' },
    { q: 'Do you prefer to give gifts or money? Why?', a: 'I prefer to give gifts', why: 'a gift shows that I really care about the person', ex: 'it also makes a special memory' },
    { q: 'What do you think is the most important thing when choosing a gift? Why?', a: 'I think the most important thing is the person\'s taste', r1: 'the gift should be something the person really needs or likes', r2: 'a thoughtful gift can make the person really happy', ex: 'I once gave my friend a book by her favorite author, and she loved it' } ] },
  { id: 'p3-15', topic: '날씨 · 계절', intro: I3('the weather and seasons', 'a weather channel'), questions: [
    { q: 'What is your favorite season, and why?', a: 'My favorite season is fall', why: 'the weather is cool and perfect for outdoor activities', ex: 'I love hiking when the leaves change color' },
    { q: 'How does the weather affect your daily activities?', a: 'When the weather is bad, I usually stay at home', why: 'I don\'t like getting wet in the rain', ex: 'on rainy days, I watch movies at home' },
    { q: 'What do you usually do to prepare for very hot summer weather? Why?', a: 'I do two things to prepare for hot summer weather', r1: 'I always carry a water bottle to stay healthy', r2: 'I stay inside in the afternoon, because it is too hot to go out', ex: 'last summer, it was over thirty-five degrees, so I spent a lot of time in cool cafés' } ] },
  { id: 'p3-16', topic: 'SNS · 인터넷', intro: I3('social media', 'a technology company'), questions: [
    { q: 'How often do you use social media, and which app do you use the most?', a: 'I use social media every day, and I use Instagram the most', why: 'I can easily see what my friends are doing', ex: 'I usually check it before going to bed' },
    { q: 'Do you post pictures on social media? Why or why not?', a: 'Yes, I sometimes post pictures on social media', why: 'I want to share special moments with my friends', ex: 'I usually post pictures of my trips' },
    { q: 'What are the advantages of using social media for businesses? Explain.', a: 'I think social media has two big advantages for businesses', r1: 'businesses can advertise to many people at a low cost', r2: 'they can communicate with customers quickly', ex: 'a small bakery near my house became famous after posting pictures of their cakes on Instagram' } ] },
  { id: 'p3-17', topic: '배달 음식', intro: I3('food delivery', 'a food delivery company'), questions: [
    { q: 'How often do you order food for delivery, and what do you usually order?', a: 'I order food for delivery about once a week, and I usually order chicken', why: 'it is quick and easy', ex: 'I usually order it on Friday night' },
    { q: 'Do you prefer to order food or cook at home? Why?', a: 'I prefer to cook at home', why: 'it is healthier and cheaper', ex: 'I can choose fresh ingredients myself' },
    { q: 'What are the disadvantages of ordering food for delivery? Explain.', a: 'I think there are two disadvantages of ordering food for delivery', r1: 'it is expensive because of the delivery fee', r2: 'delivery food is often unhealthy, with a lot of salt and oil', ex: 'last month, I spent too much money on delivery food, so I decided to cook more often' } ] },
  { id: 'p3-18', topic: '박물관 · 미술관', intro: I3('museums', 'a cultural center'), questions: [
    { q: 'When was the last time you visited a museum, and what did you see?', a: 'The last time I visited a museum was three months ago, and I saw a painting exhibition', why: 'my friend recommended it to me', ex: 'the paintings were really beautiful' },
    { q: 'Do you prefer to look around a museum by yourself or with a guided tour? Why?', a: 'I prefer to look around by myself', why: 'I can stay longer at the things I like', ex: 'I can take my time and relax' },
    { q: 'What could museums do to attract more young people? Why?', a: 'I think museums should use more technology', r1: 'young people like interactive experiences with videos and screens', r2: 'museums could offer student discounts, because students don\'t have much money', ex: 'I visited a museum with a VR experience last year, and it was really fun' } ] },
  { id: 'p3-19', topic: '자전거', intro: I3('riding bicycles', 'a sports company'), questions: [
    { q: 'How often do you ride a bicycle, and where do you usually ride it?', a: 'I ride a bicycle about once a week along the river', why: 'there is a nice bike path near my house', ex: 'I usually ride on Sunday mornings' },
    { q: 'Would you ride a bike to work or school? Why or why not?', a: 'Yes, I would ride a bike to work', why: 'it is good for my health and saves money', ex: 'I wouldn\'t have to pay for the bus' },
    { q: 'What could your city do to encourage more people to ride bicycles? Why?', a: 'I think the city should build more bike lanes', r1: 'safe bike lanes would make people feel less worried about cars', r2: 'the city could offer cheap bike rentals, so anyone can ride easily', ex: 'Seoul has a bike rental service, and I use it often because it is cheap and convenient' } ] },
  { id: 'p3-20', topic: '미용실 · 헤어', intro: I3('hair salons', 'a beauty company'), questions: [
    { q: 'How often do you get a haircut, and where do you usually go?', a: 'I get a haircut about once every two months at a salon near my house', why: 'it is close and the prices are reasonable', ex: 'I have been going there for three years' },
    { q: 'Do you usually go to the same hair salon? Why or why not?', a: 'Yes, I usually go to the same hair salon', why: 'the stylist knows exactly what I like', ex: 'I don\'t have to explain my style every time' },
    { q: 'What is the most important thing when choosing a hair salon? Why?', a: 'I think the stylist\'s skill is the most important thing', r1: 'a bad haircut can ruin my mood for weeks', r2: 'a skilled stylist can recommend a style that suits me', ex: 'I once went to a cheap salon, and I was very disappointed with my haircut' } ] }
];
