/* PART 4 · 제공된 정보로 답하기 (Q8·Q9 15초 / Q10 30초, Q10은 두 번 들려줌)
   a: 핵심 답 · plus: 한 문장 추가(IH·AL)
   {{ }} 로 감싼 부분은 외워 두면 좋은 템플릿 표현이에요. */
BANK.part4 = [
  { id: 'p4-01', cat: 'event', topic: '컨퍼런스 일정', title: 'Regional Marketing Conference', subtitle: 'Friday, May 16 · Grand Harbor Hotel, Ballroom B\nRegistration Fee: $120 (lunch included)',
    table: { head: ['Time', 'Session', 'Speaker'], rows: [['9:00 – 9:30 A.M.', 'Registration & Welcome Coffee', ''], ['9:30 – 10:30 A.M.', 'Keynote: The Future of Digital Advertising', 'Sarah Kim'], ['10:30 – 11:30 A.M.', 'Workshop: Social Media Strategies for Small Businesses', 'David Lee'], ['11:30 A.M. – 12:30 P.M.', 'Lunch', ''], ['12:30 – 1:30 P.M.', 'Panel Discussion: Customer Data and Privacy', 'Emily Park, James Wilson'], ['1:30 – 2:30 P.M.', 'Workshop: Creating Effective Video Ads', 'David Lee'], ['2:30 – 3:00 P.M.', 'Closing Remarks', 'Sarah Kim']] },
    narrator: 'Hi, I\'m planning to attend the marketing conference, but I don\'t have the schedule with me. I was hoping you could answer a few questions.',
    questions: [
      { q: 'Where will the conference be held, and what time does it start?', a: '{{The conference will be held}} at the Grand Harbor Hotel, in Ballroom B, {{and it starts at}} 9 A.M.', plus: 'It begins with registration and a welcome coffee.' },
      { q: 'I heard that I have to pay for lunch separately. Is that right?', a: 'Lunch is included in the registration fee of 120 dollars, {{so you don\'t have to}} pay extra.' },
      { q: 'I\'m interested in David Lee\'s sessions. Could you tell me about the sessions he is leading?', a: '{{There are two}} sessions led by David Lee. {{First, at}} 10:30 A.M., {{there is a}} workshop on social media strategies for small businesses. {{Second, at}} 1:30 P.M., {{there is a}} workshop on creating effective video ads.' } ] },
  { id: 'p4-02', cat: 'interview', topic: '면접 일정', title: 'Hanson Electronics — Interview Schedule', subtitle: 'Thursday, October 9 · Conference Room 3',
    table: { head: ['Time', 'Candidate', 'Position', 'Current Employer'], rows: [['9:00 A.M.', 'Rachel Moore', 'Sales Manager', 'ABC Retail'], ['10:00 A.M.', 'Kevin Tran', 'Accountant', 'Lakeside Bank'], ['11:00 A.M.', 'Maria Lopez', 'Sales Manager', 'Freelance  ※ Rescheduled to Oct. 10'], ['1:00 P.M.', 'Daniel Cho', 'Software Engineer', 'NextGen Tech'], ['2:00 P.M.', 'Laura Evans', 'Sales Manager', 'Metro Mart']] },
    narrator: 'Hi, this is Tom from the sales department. I\'m going to help with the interviews on Thursday, but I left the schedule at home.',
    questions: [
      { q: 'What time is the first interview, and where will the interviews take place?', a: '{{The first interview is at}} 9 A.M., {{and all the interviews will take place in}} Conference Room 3.' },
      { q: 'I believe I\'m interviewing Maria Lopez at 11 o\'clock on Thursday. Is that correct?', a: 'Maria Lopez\'s interview {{has been rescheduled to}} Friday, October 10th.', plus: 'So you won\'t meet her on Thursday.' },
      { q: 'Could you give me the details about the candidates for the sales manager position on Thursday?', a: '{{There are two}} candidates for the sales manager position. {{First, at}} 9 A.M., {{you will meet}} Rachel Moore, {{who currently works at}} ABC Retail. {{Second, at}} 2 P.M., {{you will meet}} Laura Evans, {{who currently works at}} Metro Mart.' } ] },
  { id: 'p4-03', cat: 'personal', topic: '출장 일정', title: 'Business Trip Itinerary — Jennifer Walsh', subtitle: 'Destination: Chicago · Hotel: Parkview Hotel',
    table: { head: ['Date', 'Time', 'Schedule'], rows: [['Mon, March 3', '7:30 A.M.', 'Depart Boston (Flight 204) → Arrive Chicago 9:45 A.M.'], ['', '1:00 P.M.', 'Meeting with sales team (Chicago branch)'], ['Tue, March 4', '10:00 A.M.', 'Product presentation to Lakeview Foods'], ['', '6:00 P.M.', 'Dinner with client (Riverfront Grill)'], ['Wed, March 5', '11:00 A.M.', 'Factory tour (Westside plant)'], ['', '4:30 P.M.', 'Depart Chicago (Flight 331) → Arrive Boston 7:40 P.M.']] },
    narrator: 'Hi, this is Jennifer. I\'m going on a business trip to Chicago next week, but I can\'t find my itinerary.',
    questions: [
      { q: 'What time does my flight leave on Monday, and when will I arrive in Chicago?', a: '{{Your flight leaves}} Boston at 7:30 A.M. on Monday, {{and you will arrive in}} Chicago at 9:45 A.M.' },
      { q: 'I\'d like to meet a friend on Tuesday evening. Am I free then?', a: '{{You have}} a dinner with a client at 6 P.M. at Riverfront Grill on Tuesday.', plus: 'So you might want to meet your friend another time.' },
      { q: 'Can you tell me everything I\'ll be doing on Wednesday?', a: '{{You have two things on}} Wednesday. {{First, at}} 11 A.M., {{you will}} take a factory tour at the Westside plant. {{Second, at}} 4:30 P.M., {{you will}} leave Chicago on Flight 331 and arrive in Boston at 7:40 P.M.' } ] },
  { id: 'p4-04', cat: 'class', topic: '강좌 시간표', title: 'Greenwood Community Center — Spring Classes', subtitle: 'March 3 – May 30 · Fee: $50 per class (members 20% off)',
    table: { head: ['Class', 'Day', 'Time', 'Instructor'], rows: [['Beginner Yoga', 'Monday', '7:00 – 8:00 P.M.', 'Amy Scott'], ['Watercolor Painting', 'Tuesday', '6:30 – 8:00 P.M.', 'Brian Hall'], ['Healthy Cooking', 'Wednesday', '7:00 – 9:00 P.M.', 'Linda Park'], ['Advanced Yoga', 'Thursday', '7:00 – 8:00 P.M.', 'Amy Scott'], ['Photography Basics', 'Saturday', '10:00 A.M. – 12:00 P.M.', 'Brian Hall']] },
    narrator: 'Hi, I\'m interested in taking a class at the community center this spring. Could you give me some information?',
    questions: [
      { q: 'When do the spring classes start, and how much is each class?', a: '{{The spring classes start on}} March 3rd, {{and each class costs}} 50 dollars.', plus: 'Members can get a 20 percent discount.' },
      { q: 'I work until 7 on weekdays, so I can only take a class on the weekend. Is there a class I can take?', a: '{{Yes, there is}} a Photography Basics class on Saturday from 10 A.M. to 12 P.M.', plus: 'It is taught by Brian Hall.' },
      { q: 'I heard Amy Scott is a great teacher. Could you tell me about all the classes she teaches?', a: '{{There are two}} classes taught by Amy Scott. {{First,}} Beginner Yoga is on Monday from 7 to 8 P.M. {{Second,}} Advanced Yoga is on Thursday from 7 to 8 P.M.' } ] },
  { id: 'p4-05', cat: 'resume', topic: '이력서', title: 'Resume — Jessica Moore', subtitle: 'Applying for: Marketing Manager',
    table: { head: ['Category', 'Details'], rows: [['Education', 'M.A. in Marketing, Brighton University (2018)'], ['', 'B.A. in Business, Lakeside College (2015)'], ['Experience', 'Marketing Manager, Blue Ocean Travel (2021 – present)'], ['', 'Marketing Assistant, Star Foods (2018 – 2021)'], ['Skills', 'Social media marketing, data analysis, fluent in Spanish'], ['Awards', 'Best New Campaign Award (2022)']] },
    narrator: 'Hi, I\'m going to interview Jessica Moore this afternoon, but I don\'t have her resume with me. Can you help me?',
    questions: [
      { q: 'Where did Jessica get her master\'s degree, and when did she get it?', a: '{{She got her master\'s degree in}} Marketing {{from}} Brighton University {{in}} 2018.' },
      { q: 'I heard she doesn\'t have any experience as a manager. Is that right?', a: '{{She has been working as}} a marketing manager at Blue Ocean Travel since 2021.' },
      { q: 'Could you tell me about her work experience?', a: '{{She has two work experiences.}} {{First, from}} 2018 {{to}} 2021, {{she worked as}} a marketing assistant at Star Foods. {{Second, since}} 2021, {{she has been working as}} a marketing manager at Blue Ocean Travel.' } ] },
  { id: 'p4-06', cat: 'personal', topic: '병원 예약', title: 'Dr. Kim\'s Schedule — Riverside Clinic', subtitle: 'Tuesday, June 10',
    table: { head: ['Time', 'Patient', 'Reason'], rows: [['9:00 A.M.', 'Brian Lee', 'Check-up'], ['9:30 A.M.', 'Susan Park', 'Flu symptoms'], ['10:30 A.M.', 'Mark Davis', 'Knee pain  ※ Canceled'], ['11:00 A.M.', 'Emma Wilson', 'Check-up'], ['1:00 – 2:00 P.M.', 'Lunch', ''], ['2:00 P.M.', 'Tom Harris', 'Back pain'], ['3:00 P.M.', 'Staff meeting', '']] },
    narrator: 'Hi, this is Dr. Kim. I\'m on my way to the clinic, and I\'d like to check my schedule for today.',
    questions: [
      { q: 'Who is my first patient, and what time is the appointment?', a: '{{Your first patient is}} Brian Lee, {{and the appointment is at}} 9 A.M.', plus: 'He is coming for a check-up.' },
      { q: 'I think I have an appointment with Mark Davis at 10:30. Is that right?', a: 'Mark Davis {{canceled his appointment}}, so you are free at 10:30.' },
      { q: 'What do I have scheduled for the afternoon?', a: '{{You have two things in}} the afternoon. {{First, at}} 2 P.M., {{you will see}} Tom Harris for back pain. {{Second, at}} 3 P.M., {{you have}} a staff meeting.' } ] },
  { id: 'p4-07', cat: 'class', topic: '신입사원 교육', title: 'New Employee Orientation', subtitle: 'Monday, April 7 · Room 201 · Lunch provided',
    table: { head: ['Time', 'Session', 'Presenter'], rows: [['9:00 – 9:30 A.M.', 'Welcome Speech', 'CEO Richard Brown'], ['9:30 – 10:30 A.M.', 'Company History and Vision', 'Karen White'], ['10:30 – 12:00 P.M.', 'Computer System Training', 'IT Team'], ['12:00 – 1:00 P.M.', 'Lunch', ''], ['1:00 – 2:00 P.M.', 'Safety Training', 'Paul Green'], ['2:00 – 3:00 P.M.', 'Office Tour', 'Karen White']] },
    narrator: 'Hi, I\'m a new employee, and I\'m going to attend the orientation next week. I have a few questions.',
    questions: [
      { q: 'What date is the orientation, and where will it be held?', a: '{{The orientation is on}} Monday, April 7th, {{and it will be held in}} Room 201.' },
      { q: 'Should I bring my own lunch?', a: '{{You don\'t have to}} bring your own lunch, {{because}} lunch is provided.' },
      { q: 'I heard Karen White is my manager. Could you tell me about the sessions she is leading?', a: '{{There are two}} sessions led by Karen White. {{First, from}} 9:30 {{to}} 10:30 A.M., {{she will talk about}} the company\'s history and vision. {{Second, from}} 2 {{to}} 3 P.M., {{she will give}} an office tour.' } ] },
  { id: 'p4-08', cat: 'personal', topic: '호텔 예약 확인', title: 'Sunset Beach Resort — Reservation Confirmation', subtitle: 'Guest: Mr. Daniel Cho · Confirmation #4821',
    table: { head: ['Item', 'Details'], rows: [['Check-in', 'Friday, July 18, after 3:00 P.M.'], ['Check-out', 'Sunday, July 20, before 11:00 A.M.'], ['Room', 'Ocean View Double Room'], ['Price', '$180 per night (breakfast included)'], ['Free Services', 'Airport shuttle, swimming pool, Wi-Fi'], ['Extra Services', 'Spa ($60), Bicycle rental ($15 per day)']] },
    narrator: 'Hi, I made a reservation at your resort, but I lost my confirmation email. Could you check some details for me?',
    questions: [
      { q: 'What time can I check in, and when do I need to check out?', a: '{{You can check in after}} 3 P.M. on Friday, July 18th, {{and you need to check out before}} 11 A.M. on Sunday.' },
      { q: 'I heard that breakfast costs extra. Is that right?', a: 'Breakfast is included in the room price of 180 dollars per night, {{so you don\'t have to}} pay extra.' },
      { q: 'Could you tell me about the free services at the resort?', a: '{{There are three}} free services. {{First,}} there is a free airport shuttle. {{Second,}} you can use the swimming pool. {{Lastly,}} Wi-Fi is also free.' } ] },
  { id: 'p4-09', cat: 'event', topic: '도서 박람회', title: 'City Book Fair', subtitle: 'Saturday, September 20 · City Convention Center · Admission: $10 (children under 12 free)',
    table: { head: ['Time', 'Event', 'Location'], rows: [['10:00 A.M.', 'Opening Ceremony', 'Main Hall'], ['11:00 A.M.', 'Book Signing: Mary Johnson', 'Room A'], ['1:00 P.M.', 'Children\'s Story Time', 'Room B'], ['2:00 P.M.', 'Talk: How to Write a Best-seller (Mary Johnson)', 'Main Hall'], ['4:00 P.M.', 'Used Book Sale', 'Lobby']] },
    narrator: 'Hi, I\'m thinking of going to the book fair with my family. Can you answer some questions?',
    questions: [
      { q: 'Where is the book fair, and how much is admission?', a: '{{The book fair is at}} the City Convention Center, {{and admission is}} 10 dollars.', plus: 'Children under 12 can enter for free.' },
      { q: 'My kids are 8 and 10. I heard we have to pay 10 dollars for each of them. Is that correct?', a: 'Children under 12 {{can enter for free}}, so you don\'t have to pay for your kids.' },
      { q: 'I\'m a big fan of Mary Johnson. Can you tell me about the events related to her?', a: '{{There are two}} events related to Mary Johnson. {{First, at}} 11 A.M., {{there is a}} book signing in Room A. {{Second, at}} 2 P.M., {{she will give a}} talk about how to write a best-seller in the Main Hall.' } ] },
  { id: 'p4-10', cat: 'etc', topic: '관광 투어 일정', title: 'Historic City Walking Tour', subtitle: 'Every Saturday · Meeting point: City Hall, 9:00 A.M. · Price: $35 (lunch not included)',
    table: { head: ['Time', 'Place'], rows: [['9:00 – 10:00 A.M.', 'Old Town Square'], ['10:00 – 11:00 A.M.', 'City History Museum'], ['11:00 A.M. – 12:30 P.M.', 'Lunch break (Riverside Market)'], ['12:30 – 1:30 P.M.', 'Royal Palace'], ['1:30 – 2:30 P.M.', 'Art Street & Gift Shops']] },
    narrator: 'Hi, I\'m interested in your walking tour. I\'d like to ask a few questions before I sign up.',
    questions: [
      { q: 'Where does the tour start, and what time should I be there?', a: '{{The tour starts at}} City Hall, {{and you should be there by}} 9 A.M.' },
      { q: 'I heard lunch is included in the price. Is that right?', a: 'Lunch is not included in the tour price of 35 dollars.', plus: 'But there is a lunch break at Riverside Market.' },
      { q: 'Can you tell me about the tour schedule after lunch?', a: '{{There are two}} places to visit after lunch. {{First, from}} 12:30 {{to}} 1:30, {{you will visit}} the Royal Palace. {{Second, from}} 1:30 {{to}} 2:30, {{you will visit}} Art Street and some gift shops.' } ] },
  { id: 'p4-11', cat: 'event', topic: '사내 워크숍', title: 'Leadership Workshop', subtitle: 'Wednesday, November 12 · Room 505 · For team leaders only',
    table: { head: ['Time', 'Session', 'Speaker'], rows: [['9:00 – 10:00 A.M.', 'Effective Communication', 'Dr. Lisa Chang'], ['10:00 – 11:00 A.M.', 'Managing Time', 'Tom Baker'], ['11:00 A.M. – 12:00 P.M.', 'Solving Team Problems  ※ Canceled', 'Mike Evans'], ['12:00 – 1:00 P.M.', 'Lunch', ''], ['1:00 – 2:30 P.M.', 'Motivating Your Team', 'Dr. Lisa Chang'], ['2:30 – 3:00 P.M.', 'Q&A', 'All speakers']] },
    narrator: 'Hi, I\'m a team leader, and I\'m going to attend the leadership workshop. I have some questions about it.',
    questions: [
      { q: 'What date is the workshop, and what is the first session?', a: '{{The workshop is on}} Wednesday, November 12th, {{and the first session is}} Effective Communication {{at}} 9 A.M.' },
      { q: 'I\'m really looking forward to Mike Evans\' session on solving team problems. It\'s at 11, right?', a: 'Mike Evans\' session {{has been canceled}}.', plus: 'So you will have a free hour before lunch.' },
      { q: 'Could you tell me about the sessions led by Dr. Lisa Chang?', a: '{{There are two}} sessions led by Dr. Lisa Chang. {{First, from}} 9 {{to}} 10 A.M., {{she will talk about}} effective communication. {{Second, from}} 1 {{to}} 2:30 P.M., {{she will talk about}} motivating your team.' } ] },
  { id: 'p4-12', cat: 'personal', topic: '개인 주간 일정', title: 'Weekly Schedule — Sarah Kim', subtitle: 'Week of August 4',
    table: { head: ['Day', 'Time', 'Plan'], rows: [['Monday', '10:00 A.M.', 'Team meeting'], ['Tuesday', '3:00 P.M.', 'Dentist appointment'], ['Wednesday', '12:00 P.M.', 'Lunch with client (Mr. Park)'], ['Thursday', 'All day', 'Business trip to Busan'], ['Friday', '9:00 A.M.', 'Project report due'], ['Friday', '7:00 P.M.', 'Dinner with college friends']] },
    narrator: 'Hi, this is Sarah. I left my planner at the office. Can you check my schedule for this week?',
    questions: [
      { q: 'What do I have on Monday, and what time is it?', a: '{{You have}} a team meeting {{at}} 10 A.M. on Monday.' },
      { q: 'I\'d like to meet my sister on Thursday afternoon. Am I free?', a: '{{You are not free}} on Thursday, {{because you have}} a business trip to Busan all day.' },
      { q: 'What do I have scheduled on Friday?', a: '{{You have two things on}} Friday. {{First, by}} 9 A.M., {{you need to}} submit your project report. {{Second, at}} 7 P.M., {{you have}} dinner with your college friends.' } ] },
  { id: 'p4-13', cat: 'event', topic: '음악 축제 프로그램', title: 'Summer Music Festival', subtitle: 'July 26 – 27 · Lakeside Park · Tickets: $40 per day / $70 for both days',
    table: { head: ['Date', 'Time', 'Performer', 'Stage'], rows: [['Sat, July 26', '2:00 P.M.', 'The Blue Notes (Jazz)', 'Main Stage'], ['', '5:00 P.M.', 'City Orchestra (Classical)', 'Lake Stage'], ['', '8:00 P.M.', 'Nova (Pop)', 'Main Stage'], ['Sun, July 27', '3:00 P.M.', 'Green Hills (Folk)', 'Lake Stage'], ['', '7:00 P.M.', 'The Blue Notes (Jazz)', 'Main Stage']] },
    narrator: 'Hi, I\'m thinking about going to the summer music festival. Could you give me some details?',
    questions: [
      { q: 'Where is the festival held, and how much is a ticket?', a: '{{The festival is held at}} Lakeside Park, {{and a ticket costs}} 40 dollars per day.', plus: 'If you go both days, it is 70 dollars.' },
      { q: 'I heard Nova is performing on Sunday. Is that right?', a: 'Nova {{is performing on}} Saturday at 8 P.M. on the Main Stage, not on Sunday.' },
      { q: 'I love jazz. Can you tell me about the jazz performances?', a: '{{There are two}} jazz performances, both by The Blue Notes. {{First, on}} Saturday {{at}} 2 P.M., {{they will perform on}} the Main Stage. {{Second, on}} Sunday {{at}} 7 P.M., {{they will perform on}} the Main Stage again.' } ] },
  { id: 'p4-14', cat: 'etc', topic: '부동산 매물', title: 'Apartments for Rent — Maple Realty', subtitle: 'Contact: 555-2040 · Viewing available on weekdays',
    table: { head: ['Location', 'Size', 'Monthly Rent', 'Features'], rows: [['Downtown', '1 bedroom', '$1,200', 'Near subway, gym in building'], ['Riverside', '2 bedrooms', '$1,500', 'River view, parking'], ['Oakwood', '2 bedrooms', '$1,100', 'Near school, garden'], ['University Area', 'Studio', '$800', 'Furnished, near library']] },
    narrator: 'Hi, I\'m looking for an apartment to rent. I saw your ad, but I have some questions.',
    questions: [
      { q: 'What is the cheapest apartment, and how much is the rent?', a: '{{The cheapest apartment is}} the studio in the University Area, {{and the rent is}} 800 dollars a month.' },
      { q: 'I heard I can visit the apartments on the weekend. Is that right?', a: 'Viewings are {{only available on weekdays}}.', plus: 'You can call 555-2040 to make an appointment.' },
      { q: 'I need an apartment with two bedrooms. Can you tell me about the options?', a: '{{There are two}} apartments with two bedrooms. {{First,}} there is one in Riverside for 1,500 dollars a month, and it has a river view and parking. {{Second,}} there is one in Oakwood for 1,100 dollars a month, and it is near a school and has a garden.' } ] },
  { id: 'p4-15', cat: 'launch', topic: '제품 출시 행사', title: 'SmartHome Product Launch Event', subtitle: 'Thursday, October 2 · Star Hotel, Grand Ballroom · Free admission (registration required)',
    table: { head: ['Time', 'Program', 'Speaker'], rows: [['6:00 P.M.', 'Welcome Reception', ''], ['6:30 P.M.', 'Introduction of the SmartClean Robot', 'Kevin Park, CEO'], ['7:00 P.M.', 'Product Demonstration', 'Jenny Lim, Engineer'], ['7:30 P.M.', 'Q&A Session', 'Kevin Park, Jenny Lim'], ['8:00 P.M.', 'Dinner & Networking', '']] },
    narrator: 'Hi, I received an invitation to your product launch event. Can you give me some information?',
    questions: [
      { q: 'Where will the event be held, and do I need to pay?', a: '{{The event will be held in}} the Grand Ballroom at the Star Hotel, {{and admission is}} free.', plus: 'But you need to register in advance.' },
      { q: 'I can only arrive at 7:30. Will I miss the product demonstration?', a: '{{I\'m afraid you will miss}} the product demonstration, {{because it starts at}} 7 P.M.', plus: 'But you can still join the Q&A session at 7:30.' },
      { q: 'Could you tell me about the sessions that Kevin Park will be part of?', a: '{{There are two}} sessions with Kevin Park. {{First, at}} 6:30 P.M., {{he will introduce}} the SmartClean Robot. {{Second, at}} 7:30 P.M., {{he will answer}} questions with Jenny Lim during the Q&A session.' } ] },

  /* ── 카테고리별 3문제 이상이 되도록 추가 (2026-09) ── */
  { id: 'p4-16', cat: 'class', topic: '평생교육원 시간표', title: 'Maple Community College — Evening Classes', subtitle: 'Spring Term: March 3 – May 22 · Fee: $90 per class',
    table: { head: ['Day', 'Time', 'Class', 'Instructor', 'Room'], rows: [['Monday', '6:00 – 7:30 P.M.', 'Basic Photography', 'Sarah Kim', '101'], ['Tuesday', '7:00 – 8:30 P.M.', 'Business English', 'David Lee', '204'], ['Wednesday', '6:00 – 7:30 P.M.', 'Healthy Cooking', 'Anna Ruiz', 'Kitchen Lab'], ['Thursday', '7:00 – 8:30 P.M.', 'Business Writing', 'David Lee', '204  ※ Canceled'], ['Saturday', '10:00 – 11:30 A.M.', 'Digital Photography', 'Sarah Kim', '101']] },
    narrator: 'Hi, I\'m interested in taking some evening classes this spring. I have a few questions about the schedule.',
    questions: [
      { q: 'When does the spring term start, and how much does each class cost?', a: '{{The spring term starts on}} March 3rd, {{and each class costs}} 90 dollars.' },
      { q: 'I\'d like to take the business writing class on Thursday. That\'s still available, right?', a: '{{I\'m sorry, but}} the business writing class on Thursday {{has been canceled}}.', plus: 'But David Lee also teaches business English on Tuesdays.' },
      { q: 'I\'m interested in photography. Could you tell me about the photography classes?', a: '{{There are two}} photography classes. {{First, on}} Monday {{from}} 6 {{to}} 7:30 P.M., {{there is}} Basic Photography. {{Second, on}} Saturday {{from}} 10 {{to}} 11:30 A.M., {{there is}} Digital Photography. {{Both classes are taught by}} Sarah Kim {{in}} Room 101.' } ] },
  { id: 'p4-17', cat: 'interview', topic: '인턴 면접 일정', title: 'Greenway Bank — Internship Interviews', subtitle: 'Monday, July 7 · Room 502, 5th Floor\nInterviewers: Mark Evans, Julie Park',
    table: { head: ['Time', 'Applicant', 'Department', 'School'], rows: [['9:30 A.M.', 'Brian Hall', 'Finance', 'Stanton University'], ['10:15 A.M.', 'Emily Stone', 'Marketing', 'Hillcrest College'], ['11:00 A.M.', 'Chris Young', 'Finance', 'Stanton University'], ['11:45 A.M.', 'Lunch Break', '', ''], ['1:00 P.M.', 'Sophie Grant', 'Human Resources', 'Bayview University']] },
    narrator: 'Hello, this is Julie Park. I\'ll be interviewing internship applicants on Monday, but I don\'t have the details.',
    questions: [
      { q: 'Where will the interviews be held, and what time does the first one start?', a: '{{The interviews will be held in}} Room 502 {{on the}} 5th floor, {{and the first one starts at}} 9:30 A.M.' },
      { q: 'I think we\'ll have lunch at noon. Is that correct?', a: '{{Actually, the lunch break starts at}} 11:45 A.M., {{not at noon}}.' },
      { q: 'Could you tell me about the applicants for the finance department?', a: '{{There are two}} applicants for the finance department. {{First, at}} 9:30 A.M., {{you will meet}} Brian Hall. {{Second, at}} 11 A.M., {{you will meet}} Chris Young. {{Both of them are from}} Stanton University.' } ] },
  { id: 'p4-18', cat: 'interview', topic: '호텔 직원 면접', title: 'Seaside Resort — Job Interviews', subtitle: 'Wednesday, April 23 · Main Office, 2nd Floor',
    table: { head: ['Time', 'Candidate', 'Position', 'Experience'], rows: [['10:00 A.M.', 'Olivia Reed', 'Front Desk Clerk', '2 years'], ['10:40 A.M.', 'James Carter', 'Head Chef', '10 years'], ['11:20 A.M.', 'Nina Shah', 'Front Desk Clerk', '4 years  ※ Moved to 3:00 P.M.'], ['2:00 P.M.', 'Leo Martin', 'Tour Guide', '3 years'], ['3:40 P.M.', 'Grace Liu', 'Front Desk Clerk', '1 year']] },
    narrator: 'Hi, this is Ryan, the resort manager. I\'m going to lead the interviews on Wednesday. Can I ask you a few questions?',
    questions: [
      { q: 'What is the date of the interviews, and where will they be held?', a: '{{The interviews will be held on}} Wednesday, April 23rd, {{in the}} main office {{on the}} 2nd floor.' },
      { q: 'I\'m meeting Nina Shah at 11:20 in the morning, right?', a: '{{Actually,}} Nina Shah\'s interview {{has been moved to}} 3 P.M.', plus: 'So you will meet her in the afternoon.' },
      { q: 'Could you give me the details of the candidates for the front desk clerk position?', a: '{{There are three}} candidates for the front desk clerk position. {{First, at}} 10 A.M., {{you will meet}} Olivia Reed, {{who has}} 2 years of experience. {{Next, at}} 3 P.M., {{you will meet}} Nina Shah, {{who has}} 4 years of experience. {{Lastly, at}} 3:40 P.M., {{you will meet}} Grace Liu, {{who has}} 1 year of experience.' } ] },
  { id: 'p4-19', cat: 'resume', topic: '이력서 · 엔지니어', title: 'Resume — Kevin Nguyen', subtitle: 'Applying for: Senior Software Engineer',
    table: { head: ['Category', 'Details'], rows: [['Education', 'M.S. in Computer Science, Eastfield University (2017)'], ['', 'B.S. in Mathematics, Eastfield University (2015)'], ['Experience', 'Software Engineer, CloudPeak Inc. (2020 – present)'], ['', 'Junior Developer, AppNest (2017 – 2020)'], ['Skills', 'Java, Python, mobile app design'], ['Certificate', 'Cloud Security Certificate (2023)']] },
    narrator: 'Hi, I\'m interviewing Kevin Nguyen for the senior engineer position tomorrow. Could you check his resume for me?',
    questions: [
      { q: 'Which school did Kevin go to, and what did he study?', a: '{{He went to}} Eastfield University. {{He studied}} mathematics {{and then got a master\'s degree in}} computer science.' },
      { q: 'I heard he has only worked at one company. Is that right?', a: '{{No, he has worked at two companies,}} AppNest {{and}} CloudPeak Inc.' },
      { q: 'Could you tell me about his work experience?', a: '{{He has two work experiences.}} {{First, from}} 2017 {{to}} 2020, {{he worked as}} a junior developer at AppNest. {{Second, since}} 2020, {{he has been working as}} a software engineer at CloudPeak Inc.' } ] },
  { id: 'p4-20', cat: 'resume', topic: '이력서 · 디자이너', title: 'Resume — Hannah Scott', subtitle: 'Applying for: Graphic Designer',
    table: { head: ['Category', 'Details'], rows: [['Education', 'B.A. in Visual Design, Rosewood College (2019)'], ['Experience', 'Graphic Designer, Pixel Studio (2022 – present)'], ['', 'Design Intern, Blue Sky Magazine (2019 – 2020)'], ['Skills', 'Photoshop, Illustrator, video editing'], ['Languages', 'English, French'], ['Awards', 'Young Designer Award (2023)']] },
    narrator: 'Hello, this is Mike from the design team. I\'m meeting Hannah Scott this afternoon, but I can\'t find her resume.',
    questions: [
      { q: 'Where did Hannah go to school, and when did she graduate?', a: '{{She graduated from}} Rosewood College {{in}} 2019 {{with a degree in}} visual design.' },
      { q: 'I heard she has never won any design awards. Is that correct?', a: '{{Actually, she won}} the Young Designer Award {{in}} 2023.' },
      { q: 'Could you tell me about her skills and the languages she speaks?', a: '{{First, she can use}} Photoshop {{and}} Illustrator, {{and she also has}} video editing skills. {{Second, she speaks two languages,}} English {{and}} French.' } ] },
  { id: 'p4-21', cat: 'launch', topic: '신제품 출시 일정', title: 'Nova Phone X — Launch Plan', subtitle: 'Project Manager: Lisa Chung',
    table: { head: ['Date', 'Task', 'Team'], rows: [['August 4', 'Final product testing', 'Engineering'], ['August 18', 'Online ad campaign begins', 'Marketing'], ['September 1', 'Press conference (City Hall)', 'Public Relations'], ['September 5', 'Pre-orders open  ※ Moved to Sept. 8', 'Sales'], ['September 20', 'Phone goes on sale in stores', 'Sales']] },
    narrator: 'Hi, this is Paul from the sales department. I\'d like to check some dates for the Nova Phone X launch.',
    questions: [
      { q: 'When does the phone go on sale, and who is the project manager?', a: '{{The phone goes on sale in stores on}} September 20th, {{and the project manager is}} Lisa Chung.' },
      { q: 'Pre-orders open on September 5th, right?', a: '{{Actually, the pre-order date has been moved to}} September 8th.' },
      { q: 'What will the sales team do during the launch?', a: '{{The sales team has two tasks.}} {{First, on}} September 8th, {{they will open}} pre-orders. {{Second, on}} September 20th, {{they will start selling}} the phone in stores.' } ] },
  { id: 'p4-22', cat: 'launch', topic: '매장 오픈 준비 일정', title: 'Fresh Market — New Store Opening', subtitle: 'Location: 250 Hill Street · Opening Day: Saturday, November 15',
    table: { head: ['Date', 'Event', 'Details'], rows: [['November 3', 'Staff training', '9 A.M. – 4 P.M., Head Office'], ['November 10', 'Product delivery', 'Fresh food & household items'], ['November 14', 'VIP preview night', '6 P.M. – 8 P.M., members only'], ['November 15', 'Grand opening', 'Ribbon cutting at 10 A.M.'], ['November 15', 'Opening gift', 'Free shopping bag for first 200 customers']] },
    narrator: 'Hello, I\'m a new employee at the Hill Street store. I have a few questions about the opening schedule.',
    questions: [
      { q: 'Where is the new store, and when is the opening day?', a: '{{The new store is located at}} 250 Hill Street, {{and it opens on}} Saturday, November 15th.' },
      { q: 'I heard staff training will be held at the new store. Is that right?', a: '{{No, staff training will be held at}} the head office {{on}} November 3rd.', plus: 'It runs from 9 A.M. to 4 P.M.' },
      { q: 'What will happen on opening day?', a: '{{Two things will happen on}} opening day. {{First, at}} 10 A.M., {{there will be}} a ribbon cutting ceremony. {{Second, the first}} 200 customers {{will receive}} a free shopping bag.' } ] },
  { id: 'p4-23', cat: 'etc', topic: '당일 여행 패키지', title: 'Blue Lake Day Trip', subtitle: 'Saturday, June 21 · Price: $65 (lunch included)\nBus leaves from: Central Station, Gate 2',
    table: { head: ['Time', 'Activity'], rows: [['8:00 A.M.', 'Bus departs from Central Station'], ['10:00 A.M.', 'Boat ride on Blue Lake'], ['12:00 P.M.', 'Lunch at Lakeside Restaurant'], ['1:30 P.M.', 'Hiking at Pine Mountain (optional)'], ['1:30 P.M.', 'Shopping at Blue Lake Village'], ['5:00 P.M.', 'Return to Central Station']] },
    narrator: 'Hi, I\'m thinking about joining the Blue Lake day trip. Could you answer a few questions for me?',
    questions: [
      { q: 'How much does the trip cost, and where does the bus leave from?', a: '{{The trip costs}} 65 dollars, {{including lunch}}, {{and the bus leaves from}} Gate 2 {{at}} Central Station.' },
      { q: 'I have to pay extra for lunch, right?', a: '{{No, you don\'t have to.}} Lunch {{is included in}} the price.' },
      { q: 'What can I do in the afternoon?', a: '{{You have two options.}} {{First, at}} 1:30 P.M., {{you can go}} hiking at Pine Mountain. {{Or, at the same time, you can go}} shopping at Blue Lake Village. {{Then, at}} 5 P.M., {{the bus will return to}} Central Station.' } ] }
];
