/* PART 2 · 사진 묘사
   모범답안은 아래 조각을 "사진 묘사 템플릿"에 끼워서 IM / IH / AL 로 자동 완성돼요.
   place: 장소 · see: 가장 먼저 보이는 것 · a, b: [위치 표현, 묘사] · c: 추가 묘사(AL) · bg: 배경 · feel: 느낌(형용사) · mood: 추측(AL) */
const U = id => `https://images.unsplash.com/${id}?w=1000&q=80`;
BANK.part2 = [
  { id: 'p2-01', cat: 'office', topic: '사무실 · 회의', img: U('photo-1517048676732-d65bc937f952'),
    alt: '햇살이 드는 사무실의 긴 나무 테이블에서 여러 사람이 회의 중. 앞쪽 사람은 펜을 들고 노란 노트에 필기, 파란 스웨터를 입은 남자, 회색 스웨터를 입은 남자, 오른쪽에 흰 서류.',
    kw: ['take notes 필기하다', 'wooden table 나무 테이블', 'lean on ~에 기대다', 'sunlight 햇빛'],
    place: 'in an office', see: 'some people having a meeting at a long wooden table',
    a: ['In the front,', 'a man is taking notes in a yellow notebook'], b: ['Next to him,', 'a man in a blue sweater is resting his hands on the table'],
    c: 'a man in a gray sweater is listening carefully', bg: 'there is a big window, and the sunlight is coming in', feel: 'busy but warm', mood: 'they are having an important meeting' },
  { id: 'p2-02', cat: 'food', topic: '거리 · 야외 카페', img: U('photo-1719079198883-3900795361f5'),
    alt: '햇살 비치는 거리의 가게들 앞 인도에 야외 테이블과 의자, 여러 사람이 앉아 있음. 입간판 여러 개, 왼쪽 미용실 간판, 왼쪽 끝에 나이 든 남자.',
    kw: ['sidewalk 인도', 'outdoor tables 야외 테이블', 'sign board 입간판', 'shop 가게'],
    place: 'on a street', see: 'many tables and chairs outside the shops',
    a: ['In the middle,', 'some people are sitting at the tables and talking'], b: ['On the left,', 'an old man is sitting alone'],
    c: 'there are some sign boards in front of the shops', bg: 'I can see a row of small shops and cafés', feel: 'sunny and relaxing', mood: 'people are enjoying a peaceful afternoon' },
  { id: 'p2-03', cat: 'shop', topic: '야외 시장', img: U('photo-1670852453934-4ff54fbe77be'),
    alt: '하얀 천막들이 늘어선 야외 시장, 줄 조명, 사람들이 많이 걸어 다님. 청록색 티셔츠 남자, 회색 티셔츠 남자 뒷모습, 오른쪽 음식 가판대, 뒤쪽 큰 나무, 흐린 하늘.',
    kw: ['outdoor market 야외 시장', 'tent 천막', 'string lights 줄 조명', 'crowded 붐비는'],
    place: 'at an outdoor market', see: 'a lot of people walking between white tents',
    a: ['In the middle,', 'a man in a green T-shirt is looking at the stalls'], b: ['On the right,', 'there is a stall selling food and drinks'],
    c: 'there are string lights above the tents', bg: 'there are tall trees and a cloudy sky', feel: 'very crowded and lively', mood: 'there is a local festival today' },
  { id: 'p2-04', cat: 'outdoor', topic: '공원', img: U('photo-1667752688237-8183739ed005'),
    alt: '잔디 언덕 공원. 앞쪽 나무 벤치에 두 사람이 뒷모습으로 앉아 있음. 멀리 벤치마다 사람들, 오른쪽 벤치에 분홍 재킷 흰 모자 여자, 잎 없는 나무.',
    kw: ['wooden bench 나무 벤치', 'grass 잔디', 'with their backs to the camera 뒷모습으로', 'tree without leaves 잎 없는 나무'],
    place: 'in a park', see: 'two people sitting on a wooden bench',
    a: ['On the grass,', 'there are some other benches, and people are sitting on them'], b: ['On the right,', 'a woman in a pink jacket is relaxing on a bench'],
    c: 'some people are sitting on the grass in the distance', bg: 'there is a big tree without leaves', feel: 'calm and peaceful', mood: 'it is a sunny day in late autumn' },
  { id: 'p2-06', cat: 'street', topic: '도로 · 횡단보도', img: U('photo-1761301006704-bc013cfb1e65'),
    alt: '나무가 늘어선 도시 도로. 횡단보도를 건너는 사람들 — 왼쪽 흰 셔츠 남자, 가운데 가방 든 여자. 정차한 차들, 신호등, "ALL BUSES" 표지판.',
    kw: ['cross the street 길을 건너다', 'crosswalk 횡단보도', 'traffic light 신호등', 'lined with trees 나무가 늘어선'],
    place: 'on a city street', see: 'some people crossing the street at a crosswalk',
    a: ['In the middle,', 'a woman is carrying a big bag'], b: ['On the left,', 'a man in a white T-shirt is walking'],
    c: 'some cars are waiting for the traffic light', bg: 'there are tall green trees and a building', feel: 'bright and busy', mood: 'it is a sunny summer day' },
  { id: 'p2-07', cat: 'food', topic: '식당 · 서빙', img: U('photo-1566670735914-b2038696981d'),
    alt: '식당에서 검은 티셔츠와 회색 앞치마를 입은 웨이터가 생선 요리와 방울토마토가 담긴 접시를 들고 서빙 중. 왼쪽 앞에 앉아 있는 여자, 뒤쪽 파란 의자와 앉아 있는 손님들.',
    kw: ['waiter 웨이터', 'serve food 음식을 서빙하다', 'apron 앞치마', 'plate 접시'],
    place: 'at a restaurant', see: 'a waiter serving a plate of food',
    a: ['He', 'is wearing a black T-shirt and a gray apron'], b: ['On the left,', 'a woman is sitting at a table'],
    c: 'the plate has some fish and colorful tomatoes on it', bg: 'some people are sitting on blue chairs', feel: 'busy', mood: 'it is lunchtime at a popular restaurant' },
  { id: 'p2-08', cat: 'street', topic: '공항', img: U('photo-1687992176093-6417a93fa3d0'),
    alt: '공항 터미널. 모자·회색 티셔츠·반바지·검은 배낭의 남자와 검은 재킷·청바지·흰 가방의 여자가 큰 유리창 쪽으로 걸어가는 뒷모습. 창밖에 비행기들, 반짝이는 바닥.',
    kw: ['airport terminal 공항 터미널', 'backpack 배낭', 'walk side by side 나란히 걷다', 'airplane 비행기'],
    place: 'at an airport', see: 'a man and a woman walking together',
    a: ['On the left,', 'the man is wearing a cap and carrying a black backpack'], b: ['On the right,', 'the woman is wearing a black jacket and carrying a white bag'],
    c: 'the floor is very clean and shiny', bg: 'there are big windows, and I can see some airplanes outside', feel: 'bright and spacious', mood: 'they are going on a trip together' },
  { id: 'p2-09', cat: 'food', topic: '카페 · 직원', img: U('photo-1518473537958-1d1b23cac484'),
    alt: '카페/베이커리 카운터 안에서 흰 티셔츠와 주황 앞치마를 입은 직원 두 명이 일하는 중. 안경 쓴 여자, 곱슬머리 수염 남자가 커피 머신 사용. 둥근 조명들, 선반 위 빵과 상자, 칠판 메뉴.',
    kw: ['coffee machine 커피 머신', 'counter 카운터', 'apron 앞치마', 'hanging lights 매달린 조명'],
    place: 'in a café', see: 'two workers behind the counter',
    a: ['On the right,', 'a man with a beard is making coffee with a coffee machine'], b: ['Next to him,', 'a woman with glasses is preparing something'],
    c: 'they are both wearing white T-shirts and orange aprons', bg: 'there are many round lights and some shelves', feel: 'cozy and warm', mood: 'the café is getting ready for customers' },
  { id: 'p2-10', cat: 'school', topic: '교실 · 대학생', img: U('photo-1571260899304-425eee4c7efc'),
    alt: '강의실. 가운데 흰 셔츠·검은 배낭의 여학생이 초록 노트를 안고 서서 웃고 있음. 주변 학생들은 책상에 앉아 필기 중 — 분홍 셔츠에 안경 쓴 여학생, 오른쪽 어두운 옷 남학생.',
    kw: ['classroom 교실', 'take notes 필기하다', 'backpack 배낭', 'hold a notebook 노트를 들다'],
    place: 'in a classroom', see: 'a young woman standing and holding some notebooks',
    a: ['Around her,', 'some students are sitting at their desks and writing'], b: ['On the left,', 'a woman in a pink shirt is taking notes'],
    c: 'the standing woman is smiling and carrying a black backpack', bg: 'there is a plain white wall', feel: 'friendly', mood: 'the class is about to start' },
  { id: 'p2-11', cat: 'school', topic: '초등 교실 · 선생님', img: U('photo-1577896851231-70ef18881754'),
    alt: '초등학교 교실. 선생님이 칠판 앞에 서 있음. 학생들이 책상에 앉아 있고, 오른쪽 남학생이 손을 들고 있음. 꽃무늬 옷에 땋은 머리 여학생, 벽에 세계 지도와 포스터.',
    kw: ['blackboard 칠판', 'raise one\'s hand 손을 들다', 'map on the wall 벽의 지도', 'elementary school 초등학교'],
    place: 'in an elementary school classroom', see: 'a teacher standing in front of a blackboard',
    a: ['On the right,', 'a boy is raising his hand'], b: ['On the left,', 'a girl with braided hair is looking at the teacher'],
    c: 'many students are sitting at their desks', bg: 'there is a world map and some posters on the wall', feel: 'active', mood: 'the students are answering the teacher\'s question' },
  { id: 'p2-12', cat: 'street', topic: '공사 현장', img: U('photo-1504307651254-35680f356dfd'),
    alt: '위에서 내려다본 공사 현장. 주황 안전 조끼와 안전모를 쓴 작업자 두 명. 쇠막대(철근)가 여기저기 쌓여 있고 파란 호스/케이블.',
    kw: ['construction site 공사 현장', 'safety vest 안전 조끼', 'helmet 안전모', 'steel bars 철근'],
    place: 'at a construction site', see: 'two workers in orange safety vests',
    a: ['In the middle,', 'a worker is standing and looking down'], b: ['Behind him,', 'another worker is bending over'],
    c: 'they are both wearing safety helmets', bg: 'there are a lot of steel bars on the ground', feel: 'busy', mood: 'they are building a new building' },
  { id: 'p2-13', cat: 'office', topic: '사무실 · 컴퓨터', img: U('photo-1551434678-e076c223a692'),
    alt: '사무실에서 남자 두 명이 나란히 컴퓨터로 일함. 앞쪽 안경·수염·회색 스웨터 남자가 키보드 타이핑, 스탠드 위 노트북. 뒤쪽 어두운 스웨터 남자가 모니터를 봄. 식물, 큰 창.',
    kw: ['type on a keyboard 타이핑하다', 'monitor 모니터', 'side by side 나란히', 'plant 식물'],
    place: 'in an office', see: 'two men working on their computers',
    a: ['In the front,', 'a man with glasses is typing on a keyboard'], b: ['Behind him,', 'another man is looking at his monitor'],
    c: 'there is a laptop on a stand on the desk', bg: 'there is a big window and a green plant', feel: 'bright and quiet', mood: 'they are focusing on an important project' },
  { id: 'p2-14', cat: 'outdoor', topic: '해변 · 서핑', img: U('photo-1516370873344-fb7c61054fa9'),
    alt: '해변. 두 여자가 서핑보드를 들고 바다 쪽으로 걸어가는 중, 한 명은 팔을 들고 있음. 모래 위 발자국, 밝은 햇빛, 왼쪽 언덕.',
    kw: ['beach 해변', 'surfboard 서핑보드', 'footprints 발자국', 'waves 파도'],
    place: 'at a beach', see: 'two women walking toward the sea',
    a: ['On the left,', 'a woman is carrying a surfboard under her arm'], b: ['On the right,', 'the other woman is raising her arm'],
    c: 'there are many footprints in the sand', bg: 'I can see the waves and a small hill', feel: 'sunny and exciting', mood: 'they are going surfing together' },
  { id: 'p2-16', cat: 'shop', topic: '서점', img: U('photo-1566131807516-e3b3cd1a89d1'),
    alt: '서점. 양쪽에 2층까지 높은 책장, 뒤쪽 큰 아치형 창문. 긴 머리 여자가 카운터에 서 있는 뒷모습(줄무늬 스웨터), 카운터 위 꽃, 책을 둘러보는 손님들, 책 더미가 쌓인 테이블.',
    kw: ['bookstore 서점', 'bookshelf 책장', 'arched window 아치형 창문', 'browse 둘러보다'],
    place: 'in a bookstore', see: 'a woman standing at the counter',
    a: ['On both sides,', 'there are tall bookshelves full of books'], b: ['On the left,', 'some customers are looking at books'],
    c: 'there are some white flowers on the counter', bg: 'there is a big arched window', feel: 'classic and cozy', mood: 'it is a famous old bookstore' },
  { id: 'p2-17', cat: 'street', topic: '버스 정류장', img: U('photo-1643617526717-9a6d8716c1f7'),
    alt: '버스 정류장. 지붕 아래 사람들이 줄 서서 기다리는 중. 뒤쪽 초록·노란 버스, 앞쪽 주황·흰 줄무늬 차단봉, 갈색 재킷 여자가 걸어감, 안내 표지판.',
    kw: ['bus stop 버스 정류장', 'wait in line 줄 서서 기다리다', 'shelter 지붕 있는 대기소', 'barrier 차단봉'],
    place: 'at a bus stop', see: 'some people waiting for a bus',
    a: ['In the middle,', 'they are standing under a roof'], b: ['On the right,', 'a woman in a brown jacket is walking'],
    c: 'there are some orange barriers in front', bg: 'a green and yellow bus is coming', feel: 'busy', mood: 'it is rush hour in the morning' },
  { id: 'p2-18', cat: 'street', topic: '자전거 · 도로', img: U('photo-1764782368331-2dffc8262beb'),
    alt: '도시 도로. 두 사람이 자전거 도로에서 자전거를 타고 가는 뒷모습. 길가 나무들, 오른쪽에 주차된 버스, 노란 택시, 인도 위 사람들.',
    kw: ['ride a bike 자전거를 타다', 'bike lane 자전거 도로', 'taxi 택시', 'tree-lined 나무가 늘어선'],
    place: 'on a city street', see: 'two people riding bikes',
    a: ['On the left,', 'they are riding in a bike lane'], b: ['On the right,', 'there is a big bus parked on the road'],
    c: 'there is a yellow taxi on the street', bg: 'there are many trees and buildings', feel: 'busy', mood: 'they are riding their bikes to work' },
  { id: 'p2-19', cat: 'office', topic: '회의실 · 발표', img: U('photo-1624555130581-1d9cca783bc0'),
    alt: '회의실. 긴 테이블에 여러 사람이 앉아 있음. 앞쪽 회색 스웨터 여자, 머리에 손을 얹은 남자. 뒤쪽에서 두 여자가 화면 앞에서 발표 중. 테이블 위 커피컵, 노트, 큰 창.',
    kw: ['meeting room 회의실', 'give a presentation 발표하다', 'screen 화면', 'coffee cup 커피컵'],
    place: 'in a meeting room', see: 'some people sitting around a long table',
    a: ['In the background,', 'two women are giving a presentation'], b: ['On the left,', 'a woman in a gray sweater is listening'],
    c: 'there are some coffee cups and a notebook on the table', bg: 'there are big windows', feel: 'serious', mood: 'they are sharing ideas for a new project' },
  { id: 'p2-20', cat: 'outdoor', topic: '공원 · 피크닉', img: U('photo-1623944889288-cd147dbb517c'),
    alt: '공원 잔디 위 피크닉. 어두운 티셔츠·청바지 남자가 담요 위에 무릎 꿇고 바구니에 손을 넣음. 흰 상의 여자가 담요에 앉아 있음. 음료와 과일, 뒤쪽 건물과 나무.',
    kw: ['have a picnic 피크닉하다', 'blanket 담요', 'basket 바구니', 'lawn 잔디밭'],
    place: 'in a park', see: 'a man and a woman having a picnic',
    a: ['On the left,', 'a man in a dark T-shirt is taking something out of a basket'], b: ['On the right,', 'a woman in a white top is sitting on a blanket'],
    c: 'there are some drinks and fruit on the blanket', bg: 'I can see some trees and tall buildings', feel: 'relaxing', mood: 'they are enjoying a sunny weekend' },
  { id: 'p2-21', cat: 'shop', topic: '마트 · 쇼핑', img: U('photo-1584771145729-0bd9fda6529b'),
    alt: '마트 내부. 여자가 쇼핑 카트를 밀고 통로를 걸어감. 줄무늬 셔츠 남자가 걸어가는 중. 양쪽 진열대, 나무 진열대, 천장 조명.',
    kw: ['grocery store 마트', 'push a cart 카트를 밀다', 'aisle 통로', 'shelf 진열대'],
    place: 'in a grocery store', see: 'a woman pushing a shopping cart',
    a: ['On the right,', 'a man in a striped shirt is walking'], b: ['On the left,', 'there are shelves full of products'],
    c: 'there are some wooden displays in the middle', bg: 'there are many lights on the ceiling', feel: 'clean and bright', mood: 'they are doing their grocery shopping' },
  { id: 'p2-22', cat: 'shop', topic: '마트 · 계산대', img: U('photo-1641029956071-272caab5857a'),
    alt: '마트 계산대. 검은 후드 재킷과 장갑을 낀 여자가 컨베이어 벨트 위에 포장된 고기를 올려놓는 중. 왼쪽 빈 쇼핑 카트, 노란 계산대, 뒤쪽 마스크 쓴 사람.',
    kw: ['checkout counter 계산대', 'conveyor belt 컨베이어 벨트', 'put ~ on ~을 올려놓다', 'shopping cart 쇼핑 카트'],
    place: 'at a checkout counter', see: 'a woman putting some meat on the counter',
    a: ['On the left,', 'there is an empty shopping cart'], b: ['She', 'is wearing a black jacket and gloves'],
    c: 'the counter is yellow and black', bg: 'another person is standing near the other counter', feel: 'quiet', mood: 'she is paying for her groceries' },

  /* ── 추가 (2026-09): 카테고리마다 5장 이상이 되도록. Unsplash 무료 사진 ── */
  { id: 'p2-23', cat: 'office', topic: '사무실 · 노트북 회의', img: U('photo-1572021335469-31706a17aaef'),
    alt: '밝은 사무실의 나무 테이블에서 안경 쓴 수염 난 남자가 노트북을 하고 있음. 베이지 티셔츠 남자가 왼쪽에 서서 웃고, 남색 셔츠 남자가 뒤에 서서 화면을 가리킴. 오른쪽에 청셔츠 입은 긴 머리 여자가 웃으며 화면을 봄. 테이블 위 투명 물병, 벽에 컬러풀한 그림.',
    kw: ['gather around ~ 주위에 모이다', 'point at ~을 가리키다', 'wooden table 나무 테이블', 'painting 그림'],
    place: 'in an office', see: 'four people gathered around a laptop on a wooden table',
    a: ['In the middle,', 'a man with glasses and a beard is using a laptop'], b: ['On the right,', 'a woman with long hair is sitting and smiling at the screen'],
    c: 'a man in a dark shirt is standing behind him and pointing at the screen', bg: 'there is a colorful painting on the wall', feel: 'friendly and cheerful', mood: 'they are working together on a project' },
  { id: 'p2-24', cat: 'office', topic: '사무실 · 화이트보드 회의', img: U('photo-1681949103006-70066fb25dfe'),
    alt: '벽돌 벽과 큰 아치형 창이 있는 회의실. 검은 티셔츠의 여자가 벽의 게시판을 가리키고, 회색 티셔츠의 여자는 태블릿을 들고 앉아 있음. 체크 셔츠 남자는 펜을 들고 게시판을 보고, 오른쪽에 모자 쓴 남자가 손을 듦. 흰 테이블 위 화분, 흰 물병, 노트북.',
    kw: ['point at ~을 가리키다', 'brick wall 벽돌 벽', 'tablet 태블릿', "raise one's hand 손을 들다"],
    place: 'in a meeting room', see: 'some people having a meeting in front of a board',
    a: ['In the middle,', 'a woman in a dark T-shirt is standing and pointing at a board on the wall'], b: ['On the left,', 'a woman is sitting and holding a tablet'],
    c: 'a man in a cap is standing on the right and raising his hand', bg: 'there is a brick wall and a tall window, and a green plant is on the table', feel: 'bright and active', mood: 'they are discussing a new project' },
  { id: 'p2-25', cat: 'food', topic: '식당 · 주문 받기', img: U('photo-1777679715668-8d20edec5446'),
    alt: '레스토랑. 왼쪽 부스 자리에 흰 카디건을 입은 안경 쓴 여자가 메뉴판을 보고, 오른쪽에 베이지 스웨터 남자가 앉아 메뉴를 봄. 뒤에 앞치마를 두른 남색 셔츠 종업원이 스마트폰을 들고 서 있음. 큰 야자잎 식물, 나무 그림이 있는 벽, 왼쪽에 갈색 핸드백.',
    kw: ['take an order 주문을 받다', 'menu 메뉴판', 'apron 앞치마', 'booth 칸막이 좌석'],
    place: 'in a restaurant', see: 'a waiter taking an order from two customers',
    a: ['On the left,', 'a woman in a white cardigan is sitting and reading a menu'], b: ['On the right,', 'a man in a beige sweater is sitting at the table and looking at the menu'],
    c: 'the waiter is wearing a dark shirt and an apron', bg: 'there is a big green plant and a picture of trees on the wall', feel: 'cozy', mood: 'they are going to order lunch' },
  { id: 'p2-26', cat: 'shop', topic: '마트 · 가족 장보기', img: U('photo-1753354868403-bb9e04e74668'),
    alt: '식료품점. 앞쪽에 찢어진 청재킷과 흰 티를 입은 긴 머리 여자가 쇼핑 카트를 밀고 있고, 뒤에서 회색 셔츠에 수염 난 남자가 오른쪽 진열대의 상품을 가리킴. 카트 옆에 금발의 어린 아이. 오른쪽에 유리 용기에 담긴 식품 진열대.',
    kw: ['push a cart 카트를 밀다', 'point at ~을 가리키다', 'shelf 선반', 'grocery store 식료품점'],
    place: 'at a grocery store', see: 'a family shopping together with a cart',
    a: ['In the front,', 'a woman in a denim jacket is pushing a shopping cart'], b: ['Behind her,', 'a man in a gray shirt is pointing at some products'],
    c: 'a little boy is standing next to the cart', bg: 'there are shelves with food in glass containers', feel: 'lively', mood: 'they are choosing food for dinner' },
  { id: 'p2-27', cat: 'outdoor', topic: '공원 · 함께 조깅', img: U('photo-1758520705254-1e9d913d78ea'),
    alt: '소나무 숲이 있는 공원 길. 왼쪽에 흰 줄이 있는 검은 재킷의 여자, 오른쪽에 회색 후드티의 수염 난 남자가 함께 조깅 중. 둘 사이에 굵은 나무 기둥, 뒤쪽에 키 큰 나무와 마른 풀밭, 햇빛이 비침.',
    kw: ['jog 조깅하다', 'hoodie 후드 티', 'tree trunk 나무 기둥', 'exercise 운동하다'],
    place: 'in a park', see: 'two people jogging on a path',
    a: ['On the left,', 'a woman in a black jacket is jogging'], b: ['On the right,', 'a man in a gray hoodie is jogging next to her'],
    c: 'there is a big tree between them', bg: 'there are many tall trees and dry grass', feel: 'fresh and sunny', mood: 'they are exercising together in the morning' },
  { id: 'p2-28', cat: 'outdoor', topic: '공원 · 자전거', img: U('photo-1657891753725-6bdc1fe511c3'),
    alt: '공원의 굽은 포장길. 뒤에서 본 두 소녀가 자전거를 타고 있음. 왼쪽은 긴 검은 곱슬머리에 줄무늬 흰 원피스, 옆은 긴 금발에 줄무늬 원피스. 오른쪽 잔디에 작은 사슴, 야자수와 키 큰 나무, 오른쪽 위에서 햇빛이 비침.',
    kw: ['ride a bike 자전거를 타다', 'paved path 포장된 길', 'palm tree 야자수', 'deer 사슴'],
    place: 'in a park', see: 'two girls riding bicycles on a path',
    a: ['On the left,', 'a girl with long dark hair and a white dress is riding a bike'], b: ['Next to her,', 'a girl with long blond hair is also riding a bike'],
    c: 'a small deer is standing on the grass on the right', bg: 'there are many palm trees and green trees', feel: 'relaxing and sunny', mood: 'the girls are enjoying a peaceful evening ride' },
  { id: 'p2-29', cat: 'school', topic: '교실 · 수업 중', img: U('photo-1758270704925-fa59d93119c1'),
    alt: '교실. 앞에 회색 스웨터를 입은 수염 난 남자(선생님)가 서서 말하고 있고, 학생들이 뒷모습으로 앉아 있음. 빨간 체크 셔츠의 남자, 분홍 상의를 입은 여자, 긴 검은 머리 여자, 곱슬머리 여자. 왼쪽 위에 어두운 화면, 오른쪽에 창문과 커튼.',
    kw: ["with one's back to the camera 뒷모습으로", 'plaid shirt 체크무늬 셔츠', 'pay attention 집중하다', 'curtain 커튼'],
    place: 'in a classroom', see: 'a teacher talking to some students',
    a: ['At the front,', 'a man in a gray sweater is standing and talking'], b: ['In the foreground,', 'a man in a red plaid shirt is sitting with his back to the camera'],
    c: 'a girl in a pink top and a girl with long black hair are listening to him', bg: 'there is a dark screen on the wall and a window with curtains', feel: 'quiet and serious', mood: 'the students are paying attention to the lesson' },
  { id: 'p2-30', cat: 'school', topic: '강의실 · 손 든 학생', img: U('photo-1758270704286-83476deb3bd1'),
    alt: '큰 강의실. 왼쪽에 회색 재킷의 남자(선생님)가 학생을 향해 팔을 뻗고, 가운데 흰 스웨터를 입은 청년이 손을 듦. 파란 셔츠의 곱슬머리 여자는 필기 중, 빨간 체크 셔츠 남자와 다른 학생들이 앉아 있음. 나무 책상, 큰 창문과 커튼, 계단식 좌석.',
    kw: ["raise one's hand 손을 들다", 'lecture hall 강의실', "stretch out one's arm 팔을 뻗다", 'wooden desk 나무 책상'],
    place: 'in a big classroom', see: 'a student raising his hand in class',
    a: ['On the left,', 'a man in a gray jacket is standing and stretching out his arm'], b: ['In the middle,', 'a young man in a white sweater is raising his hand'],
    c: 'a woman with curly hair is writing in her notebook', bg: 'there are wooden desks and big windows with curtains', feel: 'active and bright', mood: 'the teacher asked a question and the student wants to answer' },

  /* ── 흑백이던 p2-05·p2-15를 컬러 사진으로 교체 (색 표현 연습을 위해 Part 2는 모두 컬러) ──
     pos = 카드에서 사진을 3:2로 자를 때 보여 줄 위치 (세로 사진에서 얼굴이 잘리지 않게) */
  { id: 'p2-31', cat: 'school', topic: '도서관 · 책 읽는 여성', img: U('photo-1752920299211-28be8c9b0121'), pos: '50% 28%',
    alt: '도서관 서가 통로. 안경을 쓴 웨이브 머리 여자가 검은 재킷, 노란 상의, 청바지 차림으로 서서 펼친 파란 책을 읽고 있음. 오른쪽에 책이 가득한 흰 서가, 뒤쪽으로 이어지는 서가, 바닥에 붉은 무늬 카펫, 천장에 밝은 조명.',
    kw: ['bookshelf 책장', 'hold an open book 펼친 책을 들다', 'aisle 통로', 'carpet 카펫'],
    place: 'in a library', see: 'a woman reading a book next to a bookshelf',
    a: ['In the middle,', 'a woman with glasses and wavy hair is holding an open book'], b: ['She', 'is wearing a black jacket, a yellow top, and jeans'],
    c: 'she is smiling a little while she reads', bg: 'there are white shelves full of books, and the carpet is red', feel: 'quiet and calm', mood: 'she is looking for some information for her study' },
  { id: 'p2-32', cat: 'food', topic: '주방 · 요리사 조리', img: U('photo-1622021142947-da7dedc7c39a'),
    alt: '레스토랑 주방. 흰 조리복과 검은 바지를 입은 요리사가 서서 초록색 도마 위에서 음식을 손질함. 스테인리스 조리대, 앞쪽 금속 볼, 오른쪽에 큰 냄비와 오븐, 뒤쪽 선반에 쌓인 흰 접시와 유리잔.',
    kw: ['cutting board 도마', "chef's jacket 조리복", 'stainless steel 스테인리스', 'stack of plates 쌓인 접시'],
    place: 'in a restaurant kitchen', see: 'a chef preparing food on a cutting board',
    a: ['In the middle,', 'a chef in a white jacket is cutting some food on a green cutting board'], b: ['In the front,', 'there is a metal bowl on the counter'],
    c: 'there are some glasses and bowls on the counter', bg: 'there are shelves with stacks of white plates', feel: 'clean and professional', mood: 'the chef is preparing a dish for a customer' }
];
// 사진은 img 폴더의 파일을 사용 (인터넷 없이도, 온라인 공유 페이지에서도 보이게). 원본 주소는 src에 보관.
BANK.part2.forEach(it => { it.src = it.img; it.img = 'img/' + it.id + '.jpg'; });
