/* PART 1 · 문장 읽기 (오리지널 지문 · 실제 시험 길이 75~90단어)
   g = 읽기 가이드:  /  짧게 쉬기   //  길게 쉬기   **굵게** = 강세   ↗ ↘ = 억양
   실제 지문은 g에서 기호를 지운 문장으로 자동 생성돼요.
   cat = 어조별 카테고리 (app.js의 CATS.1 참고) */
BANK.part1 = [
  /* ── 공지·안내 방송 ── */
  { id: 'p1-01', cat: 'notice', topic: '행사 안내', g: `Welcome to **Riverside Community Center's** / annual **spring festival**. // Throughout the day, / visitors can enjoy **live music**↗, / **handmade crafts**↗, / and **delicious local food**↘. // If you are interested in joining our **cooking class**, / please **sign up** / at the **information desk** / near the main entrance. // Children can take part in **face painting** / and **outdoor games** / in the garden behind the building. // Don't forget to visit the **art exhibition** / on the second floor / before it closes / at **five o'clock**. // We hope / you have a **wonderful day**.`, tips: ['Riverside Community Center\'s — 고유명사는 한 덩어리로', '나열 3개: music↗ crafts↗ food↘', 'exhibition [èksəbíʃən] 강세 주의'] },
  { id: 'p1-02', cat: 'notice', topic: '매장 안내 방송', g: `**Attention**, / shoppers. // Our store will be closing / in **thirty minutes**. // Please bring your final purchases / to the **checkout counters** / at the front of the store. // For faster service, / **self-checkout machines** are available / near the exit. // Also, / remember that **this week only**, / all **kitchen appliances**↗, / **furniture**↗, / and **home décor items**↘ / are **twenty percent off**. // If you have a **membership card**, / you can receive / an **extra five percent** discount. // Thank you for shopping with us, / and we hope / to see you again **soon**.`, tips: ['thirty [θɝ́ti] — thirteen과 구분', 'appliances [əpláiənsiz]', 'décor [deikɔ́ːr]'] },
  { id: 'p1-07', cat: 'notice', topic: '공항 안내 방송', g: `**Attention**, / passengers on **Flight 302** / to **Vancouver**. // Due to **bad weather**, / your flight has been **delayed** / by about **one hour**. // The new departure time / is **eleven fifteen**, / and boarding will begin / at **gate twelve**. // While you wait, / you can relax in our **cafés**↗, / **shops**↗, / and **waiting lounges**↘. // Passengers with **connecting flights** / should speak to an agent / at the **service desk**. // Please check the **display screens** / for the latest updates. // We apologize / for the **inconvenience**, / and thank you / for your **patience**.`, tips: ['Flight 302 = three oh two', 'inconvenience [ìnkənvíːnjəns]', 'Vancouver [vænkúːvər]'] },
  { id: 'p1-11', cat: 'notice', topic: '사내 공지', g: `Good morning, / everyone. // I'd like to remind you / that our **office building** / will be **closed** / this **Saturday** / for **electrical repairs**. // The work will start / at **eight a.m.** / and should be finished / by **late afternoon**. // If you need to work / during the weekend, / please do so **from home**. // Before leaving on **Friday**, / please **save your files**↗, / **turn off your computers**↗, / and **take your belongings**↘ / with you. // The **security desk** will stay open / all weekend / in case of **emergencies**. // Thank you / for your **cooperation**.`, tips: ['electrical [iléktrikəl]', 'belongings [bilɔ́ːŋiŋz]', 'cooperation [kouὰpəréiʃən]'] },
  { id: 'p1-12', cat: 'notice', topic: '도서관 안내', g: `Thank you for visiting the **Maple Public Library**. // We would like to inform you / that the library will **close** / in **fifteen minutes**. // If you wish to **borrow** any books, / please bring them / to the **front desk** now. // **Computers**↗, / **printers**↗, / and **study rooms**↘ / will be turned off / at closing time, / so please **save your work**. // You can also **renew** your books / **online** / at any time. // We are open again / **tomorrow** at **nine**, / and we hope / to see you **soon**.`, tips: ['inform [infɔ́ːrm]', 'renew [rinjúː]', 'fifteen 뒷 강세'] },
  { id: 'p1-13', cat: 'notice', topic: '호텔 안내', g: `Welcome to the **Ocean View Hotel**. // We hope / you enjoy your stay with us. // **Breakfast** is served / in the **main restaurant** / from **six thirty** / to **ten**. // Our guests can also use / the **fitness center**↗, / the **outdoor pool**↗, / and the **business lounge**↘ / **free of charge**. // A **shuttle bus** to the city center / leaves from the main entrance / **every hour**. // **Checkout time** is **eleven a.m.**, / but late checkout may be available / on request. // If you need anything, / please call the **front desk**.`, tips: ['free of charge 한 덩어리', 'shuttle [ʃʌ́tl]', 'lounge [laundʒ]'] },
  { id: 'p1-14', cat: 'notice', topic: '기차 안내 방송', g: `Ladies and gentlemen, / the train now arriving / on **platform three** / is the **express train** / to **Boston**. // This train will stop at **Stamford**↗ / and **New Haven**↘ / only. // Passengers traveling to **other stations** / should wait for the **local train**, / which departs in **ten minutes**. // **Food**↗ / and **drinks**↘ / are available / in the **café car** / in the middle of the train. // For your safety, / please stand **behind the yellow line** / and keep your **bags** with you / at all times.`, tips: ['A and B 두 개 나열: A↗ and B↘', 'express [iksprés]', 'departs [dipɑ́ːrts]'] },
  { id: 'p1-16', cat: 'notice', topic: '컨퍼런스 안내', g: `Good afternoon, / and welcome to the **annual Technology Conference**. // Today's program includes / **three workshops**↗, / **two panel discussions**↗, / and a **networking lunch**↘. // All sessions will take place / on the **second floor**, / and lunch will be served / in the **main hall** / at **twelve thirty**. // If you have not picked up / your **name badge** yet, / please visit the **registration desk**. // Before we begin, / please make sure / your **mobile phones** are turned off / or set to **silent mode**. // Enjoy the conference!`, tips: ['annual [ǽnjuəl]', 'registration [rèdʒistréiʃən]', 'silent mode 두 단어 모두 또렷이'] },
  { id: 'p1-20', cat: 'notice', topic: '기내 방송', g: `Good evening, / ladies and gentlemen. // This is your **captain** speaking. // We are now flying / at an altitude of **thirty-five thousand feet**. // We expect to arrive in **Tokyo** / **twenty minutes** ahead of schedule. // During the flight, / we will serve **dinner**↗, / **snacks**↗, / and **drinks**↘. // Please keep your **seat belt** fastened / whenever you are seated, / as we may experience / some **turbulence** later. // If you need any help, / our **flight attendants** / will be happy to assist you. // Please **relax** / and enjoy the flight.`, tips: ['altitude [ǽltətjùːd]', 'turbulence [tɝ́ːrbjələns]', 'ahead of schedule [skédʒuːl]'] },
  { id: 'p1-25', cat: 'notice', topic: '대학 오리엔테이션', g: `Welcome, / **new students**, / to **Westfield University**! // Over the next **three days**, / you will **tour the campus**↗, / **meet your professors**↗, / and **join student clubs**↘. // Please pick up your **student ID card** / at the **main hall** / this afternoon. // You will need it / to use the **library**, / the **gym**, / and the **dining hall**. // If you have any questions, / our **student volunteers** / in blue T-shirts / are happy to help. // We are **excited** / to have you here, / and we wish you **good luck** / this semester.`, tips: ['University [jùːnəvɝ́ːrsəti]', 'professors [prəfésərz]', 'semester [siméstər]'] },
  { id: 'p1-27', cat: 'notice', topic: '요리 강좌 안내', g: `Thank you for signing up / for our **weekend cooking class**. // Today, / you will learn / how to make **traditional Korean dishes**, / such as **bibimbap**↗ / and **kimchi pancakes**↘. // All **ingredients**↗ / and **cooking tools**↘ / will be provided. // Before we start, / please **wash your hands** / and put on the **apron** / on your table. // Our chef will show each step / **slowly**, / so feel free / to ask questions / at any time. // At the end of the class, / you can **enjoy the food** / you made / with your classmates.`, tips: ['ingredients [ingríːdiənts]', 'provided [prəváidid]', 'apron [éiprən]'] },
  { id: 'p1-30', cat: 'notice', topic: '마라톤 대회 안내', g: `The **annual City Marathon** / will take place / this **Sunday morning**. // More than **five thousand runners** / are expected to join the race. // Because of the event, / **Main Street**↗, / **Oak Avenue**↗, / and **River Road**↘ / will be **closed** / from **six a.m.** to **one p.m.** // Residents are asked / to **avoid driving** / in the downtown area / during these hours. // **Free buses** will run / between the **train station** / and the **finish line**. // Volunteers will hand out **water** / along the **entire route**. // Come out / and **cheer for the runners**!`, tips: ['marathon [mǽrəθὰn]', 'a.m./p.m. 또박또박', 'cheer for ~ 응원하다'] },

  /* ── 광고 ── */
  { id: 'p1-09', cat: 'ad', topic: '헬스장 광고', g: `Are you looking for a **fun way** / to stay **healthy**? // Then come to **Power Fitness**, / the newest gym / in **Oakwood**. // We offer **yoga classes**↗, / **personal training**↗, / and a **large swimming pool**↘. // Our gym is open / **twenty-four hours** a day, / so you can exercise / whenever it suits you. // This month only, / new members can join / for just **twenty dollars**. // We also have **free parking** / and **clean locker rooms** / for all members. // Visit our website / or stop by today / for a **free tour**. // Your **healthier life** / starts here!`, tips: ['의문문 끝 ↗ (Are you ~?)', 'personal [pɝ́ːrsənəl]', 'twenty 끝 t 약하게'] },
  { id: 'p1-15', cat: 'ad', topic: '쇼핑몰 광고', g: `This weekend, / **Sunrise Mall** is celebrating / its **tenth anniversary**! // Shoppers can enjoy / **special discounts**↗, / **free gifts**↗, / and **live performances**↘ / all weekend long. // More than **one hundred stores** / are offering / up to **fifty percent off**. // The first **one hundred visitors** / each day / will receive a **free shopping bag**. // **Parking** is also free / for all customers, / and the **food court** on the third floor / will offer **special meal deals** / all weekend. // Don't miss this **amazing chance** / to save money / and have fun / with your **whole family**!`, tips: ['anniversary [æ̀nəvɝ́ːrsəri]', '느낌표 문장은 밝고 힘 있게', 'performances [pərfɔ́ːrmənsiz]'] },
  { id: 'p1-17', cat: 'ad', topic: '식당 광고', g: `Are you **hungry** / after a long day at work? // Then visit **Mario's Kitchen**, / the **best Italian restaurant** in town. // We serve **fresh pasta**↗, / **homemade pizza**↗, / and **delicious desserts**↘. // All of our dishes / are made with **local ingredients** / by our **award-winning chef**. // Our cozy dining room / is perfect for **family dinners**↗, / **birthday parties**↗, / and **business lunches**↘. // Every **Monday**, / kids eat **free** / with an adult meal. // We also offer **fast delivery** / to your home or office. // Call us now / to make a **reservation**!`, tips: ['Italian [itǽljən]', 'desserts [dizɝ́ːrts] vs deserts', 'reservation [rèzərvéiʃən]'] },
  { id: 'p1-22', cat: 'ad', topic: '어학원 광고', g: `Do you want to **improve** your **English skills**? // **Global Language Center** offers classes / for **beginners**↗, / **intermediate learners**↗, / and **advanced students**↘. // All of our teachers / are **experienced** and **friendly**. // Classes are **small**, / so every student gets / plenty of **speaking practice**. // Lessons are held / on **weekday evenings** / and **Saturday mornings**, / so you can study / after work. // Our center is located / right next to **Central Station**, / so it is **easy to get to**. // Register **online** / before **March first** / and get **ten percent off**. // Don't wait, / **start learning today**!`, tips: ['intermediate [ìntərmíːdiət]', 'experienced [ikspíəriənst]', 'first 서수 발음'] },
  { id: 'p1-23', cat: 'ad', topic: '신제품 광고', g: `Introducing the new **SmartClean 500**, / the **easiest way** / to keep your home clean. // This **powerful vacuum** / is **light**↗, / **quiet**↗, / and **easy to use**↘. // It can clean your **entire house** / on a **single charge**, / and you can control it / with your **smartphone**. // It even returns / to its **charging station** / by itself, / and it comes with a **two-year warranty**. // Cleaning has never been / this **simple**! // Order today / and get a **free carrying bag**. // The SmartClean 500 / is available at **all major stores** / and **online**.`, tips: ['vacuum [vǽkjuəm]', 'entire [intáiər]', 'available [əvéiləbl]'] },
  { id: 'p1-26', cat: 'ad', topic: '레스토랑 오픈 소식', g: `**Great news** / for food lovers! // **Green Table**, / a new **vegetarian restaurant**, / will open **next Friday** / on **Park Avenue**. // The menu includes / **fresh salads**↗, / **vegetable soups**↗, / and **healthy smoothies**↘. // Everything is made / with **organic vegetables** / from nearby farms. // The restaurant will be open / **every day** / from **eleven a.m.** / to **ten p.m.** // On opening day, / every customer will receive / a **free dessert**, / and the first **fifty guests** / will get a **gift card**. // Come and try it / with your **family** and **friends**!`, tips: ['vegetarian [vèdʒətéəriən]', 'organic [ɔːrgǽnik]', 'smoothies [smúːðiz]'] },
  { id: 'p1-29', cat: 'ad', topic: '미술관 행사 홍보', g: `This **Saturday evening**, / the **Riverside Art Gallery** / will hold a **special event** / for art lovers. // Visitors can **meet local artists**↗, / **watch painting demonstrations**↗, / and **enjoy light refreshments**↘. // You will also have the chance / to **buy original paintings** / at **special prices**. // Local musicians / will also perform **live jazz** / throughout the evening. // The event starts / at **six o'clock** / and is **free** / for **gallery members**. // **Space is limited**, / so please reserve your spot / **in advance** / on our **website**. // We look forward / to seeing you there!`, tips: ['demonstrations [dèmənstréiʃənz]', 'refreshments [rifréʃmənts]', 'original [ərídʒənəl]'] },

  /* ── 뉴스·보도 ── */
  { id: 'p1-03', cat: 'news', topic: '교통 방송', g: `Good morning, / and thanks for **tuning in** / to the **morning traffic report**. // Due to **heavy rain** overnight, / several roads in the **downtown area** / are currently **closed**. // Drivers heading to the **airport**↗, / the **stadium**↗, / or the **convention center**↘ / should expect **delays** / of up to **forty minutes**. // City workers are **clearing the roads** now, / and they should reopen / **before noon**. // Until then, / we recommend taking **public transportation** / or leaving home **earlier than usual**. // Stay tuned / for more updates.`, tips: ['A, B, or C 도 ↗ ↗ ↘', 'forty(40) vs fourteen(14)', 'currently [kɝ́ːrəntli]'] },
  { id: 'p1-10', cat: 'news', topic: '일기 예보', g: `Here is your **weekend weather forecast**. // On **Saturday**, / it will be **sunny** and **warm**, / with a high of **twenty-five degrees**. // It's a great day / for **hiking**↗, / **biking**↗, / or **having a picnic**↘. // However, / on **Sunday**, / we expect **strong winds** / and **heavy rain** / in the afternoon. // Some areas near the coast / may even see **flooding**, / so please **drive carefully**. // The rain will stop / by **Monday morning**. // So, / if you go out on Sunday, / don't forget / to bring an **umbrella**.`, tips: ['degrees [digríːz]', 'However, 뒤 짧게 쉬기', 'flooding [flʌ́diŋ]'] },
  { id: 'p1-24', cat: 'news', topic: '지역 뉴스', g: `In **local news**, / the city has announced plans / to build a **new public library** / on **Main Street**. // The library will include / a **children's section**↗, / a **computer lab**↗, / and a **rooftop garden**↘. // It will also offer / **free classes** for adults / in the evenings. // Construction will begin / **next spring** / and is expected to be finished / within **two years**. // The mayor said / the project will create / more than **two hundred jobs**. // Residents are **excited** / about the new library.`, tips: ['announced [ənáunst]', 'construction [kənstrʌ́kʃən]', 'residents [rézədənts]'] },

  /* ── 인물 소개 ── */
  { id: 'p1-06', cat: 'intro', topic: '연사 소개', g: `Tonight, / it is my **great pleasure** / to introduce our **guest speaker**, / **Dr. Michael Chen**. // Dr. Chen is a **respected scientist**↗, / an **award-winning author**↗, / and a **popular lecturer**↘. // For the past **ten years**, / he has studied / how **technology** changes / the way people **communicate**. // His latest book / has been translated / into **twelve languages**. // Tonight, / he will share / some of his **new ideas** / with us, / and after his talk, / there will be time / for **questions**. // Please join me / in giving a **warm welcome** / to Dr. Chen.`, tips: ['Dr. = Doctor', 'award-winning 한 단어처럼', 'communicate [kəmjúːnəkèit]'] },
  { id: 'p1-18', cat: 'intro', topic: '수상자 소개', g: `It's my **honor** / to present this year's **Employee of the Year Award** / to **Jessica Brown** / from the **marketing team**. // Jessica has worked / with our company / for **eight years**. // She is **creative**↗, / **hardworking**↗, / and always **ready to help** others↘. // Last year, / she led our **new advertising campaign**, / which **doubled** our online sales. // Her team members say / she makes every project **fun**. // Along with the award, / Jessica will receive / a **weekend trip** for two. // Please give her / a **big round of applause**.`, tips: ['honor [ɑ́nər] h 묵음', 'Employee [implɔ́iiː]', 'applause [əplɔ́ːz]'] },
  { id: 'p1-31', cat: 'intro', topic: '신임 매니저 소개', g: `Good morning, / everyone. // I'm happy to introduce / our new **sales manager**, / **Daniel Park**. // Daniel joins us / from **Brightline Electronics**, / where he worked / for **six years**. // He has experience in **marketing**↗, / **customer service**↗, / and **international sales**↘. // He also speaks **three languages**, / which will help us / as we grow in **Asia**. // Starting next week, / he will also lead / our **Monday sales meetings**. // Daniel will be working / on the **fourth floor**, / so please stop by / and say hello. // Let's give him / a **warm welcome** / to our team.`, tips: ['introduce [ìntrədjúːs]', 'international [ìntərnǽʃənəl]', 'languages [lǽŋgwidʒiz]'] },

  /* ── 투어·가이드 ── */
  { id: 'p1-04', cat: 'tour', topic: '식물원 투어', g: `Thank you for joining **today's tour** / of the **Greenfield Botanical Garden**. // Over the next hour, / we'll walk through the **rose garden**↗, / the **tropical greenhouse**↗, / and the famous **Japanese pond**↘. // Please stay on the **marked paths** / and **do not touch** / any of the plants. // There are **benches** along the way / if you need to rest. // Photos are welcome, / but please **turn off your flash** / inside the greenhouse. // At the end of the tour, / you are welcome to visit our **gift shop** / for **seeds**↗, / **books**↗, / and **souvenirs**↘.`, tips: ['Botanical [bətǽnikəl]', 'souvenirs [sùːvəníərz]', '한 문장에 나열 두 번'] },
  { id: 'p1-08', cat: 'tour', topic: '박물관 안내', g: `Welcome to the **City History Museum**. // Our museum is open / from **Tuesday** to **Sunday**, / from **nine** to **six**. // On the first floor, / you can see **old photographs**↗, / **maps**↗, / and **traditional clothing**↘. // The second floor / shows how our city / has **changed** over the past **two hundred years**. // **Guided tours** start every hour / at the main lobby, / and **audio guides** are available / in **five languages**. // Please remember / that **food and drinks** / are **not allowed** / inside the galleries.`, tips: ['from A to B 짝으로 읽기', 'photographs [fóutəgræ̀fs]', 'galleries [gǽləriz]'] },
  { id: 'p1-21', cat: 'tour', topic: '국립공원 안내', g: `Welcome to **Pine Hill National Park**. // For your safety, / please stay on the **hiking trails** / at all times. // **Camping**↗, / **fishing**↗, / and **cooking**↘ / are only allowed / in **designated areas**. // Maps are available / at the **visitor center**, / where you can also join / a **free walking tour** / with one of our **rangers**. // The tour starts / at **ten o'clock** / every morning. // Please remember / that **wild animals** live here, / so **do not feed** them. // Please help us / keep the park **clean** / by taking your **trash** with you.`, tips: ['designated [dézignèitid]', 'rangers [réindʒərz]', 'at all times 한 덩어리'] },

  /* ── 음성 메시지 ── */
  { id: 'p1-05', cat: 'voice', topic: '병원 예약 확인', g: `Hello, / this is **Karen** / calling from **Bright Smile Dental Clinic**. // I'm calling to **remind** you / of your **appointment** / **tomorrow** at **ten thirty**. // Please arrive **fifteen minutes early** / to fill out a short **health form**. // Also, / remember to bring / your **insurance card** / and a list of any **medicine** / you are taking. // If you need to **cancel**↗ / or **reschedule**↘, / call us at least **twenty-four hours** / in advance. // Our office is open / until **six** today. // We look forward / to seeing you. // Have a **great day**.`, tips: ['A or B: A↗ or B↘', 'reschedule [rìːskédʒuːl]', 'fifteen(15) vs fifty(50)'] },
  { id: 'p1-19', cat: 'voice', topic: '정비소 음성 메시지', g: `Hi, / this is **Tom** / from **Quick Auto Repair**. // I'm calling to let you know / that your **car is ready**. // We **changed the oil**↗, / **replaced the brakes**↗, / and **checked the tires**↘. // The total cost / is **two hundred and fifty dollars**, / which is **less** / than we first expected. // You can pick up your car / **anytime** before **seven p.m.** today. // We are **closed** tomorrow, / so please come in / **this evening** if you can. // If you have any questions, / please give me a call.`, tips: ['p.m. = [piː ém]', 'replaced [ripléist]', 'brakes vs breaks 같은 발음'] },
  { id: 'p1-28', cat: 'voice', topic: '고객센터 자동 응답', g: `Thank you for calling **Star Mobile** / **customer service**. // Your call is **important** to us. // If you want to check your **bill**, / **press one**. // If you want to **change your plan**, / **press two**. // For **technical support**, / **press three**. // To report a **lost** or **stolen phone**, / **press four**. // You can also find answers / to common questions / on our **website** / or **mobile app**. // Please note / that our **office hours** are / **nine a.m.** to **eight p.m.**, / **Monday** through **Saturday**. // To speak with a **customer service representative**, / please **stay on the line**.`, tips: ['representative [rèprizéntətiv]', 'press one / press two 리듬 맞추기', 'technical [téknikəl]'] },

  /* ── 추가 (2026-09): 실제 시험 길이(75~90단어) ── */
  { id: 'p1-32', cat: 'news', topic: '경제 뉴스', g: `In **business news**, / a local company has announced / that it will open a **new factory** / in **Greenville** next year. // The factory will produce **electric bikes**↗, / **solar panels**↗, / and **battery chargers**↘. // The company expects to hire / more than **five hundred workers**, / and it will begin accepting applications / next **month**. // The **mayor** said / the project will bring / new **opportunities** / to the community. // Experts believe / the factory will also help / the **local economy** grow. // Interested applicants / can visit the company's **website** / for more information.`, tips: ['announced [ənáunst]', 'opportunities [àpərtjúːnətiz]', 'A, B, and C 나열: ↗ ↗ ↘'] },
  { id: 'p1-33', cat: 'news', topic: '건강 뉴스', g: `Here is today's **health report**. // A new study from **Westbrook University** / shows that walking for **thirty minutes** a day / can improve both **sleep**↗ / and **mood**↘. // Researchers followed more than **two thousand adults** / for **one year**. // Those who walked regularly / felt **less tired** / and had **less stress** / than those who did not. // Doctors recommend / that people start with **short walks** / and slowly increase / the time each week. // We will have more health news / after the break.`, tips: ['Researchers [risə́ːrtʃərz] 강세 둘째 음절', 'thirty(30) vs thirteen(13)', 'both A and B: A↗ and B↘'] },
  { id: 'p1-34', cat: 'intro', topic: '작가 소개', g: `Good evening, / everyone, / and welcome to the **Lakeside Book Club**. // Tonight, / we are **honored** / to have **Sarah Miller** with us. // Sarah is a **bestselling author**↗, / a **former teacher**↗, / and a **mother of three**↘. // Her latest book, / A Year in Paris, / tells the story of a young woman / who moves abroad / to follow her **dream**. // After her talk, / Sarah will sign copies of her books / near the **entrance**. // Light **refreshments** / will be served / in the lobby / after the event. // Please give her / a **warm welcome**.`, tips: ['honored [ɑ́nərd] h 묵음', 'bestselling 한 단어처럼 (베스트셀링)', 'entrance [éntrəns] 강세 첫 음절'] },
  { id: 'p1-35', cat: 'intro', topic: '은퇴 축하 소개', g: `Good afternoon, / everyone. // Today, / we are here to **celebrate** / the **retirement** of **Mr. Robert Lee**. // Mr. Lee has worked / for our company / for **thirty years**. // He started as a **delivery driver**, / and he later became / our **operations director**. // He is **kind**↗, / **patient**↗, / and always **willing to help**↘. // We will **miss** him very much, / and we wish him / a **happy and healthy** retirement. // There will be **cake** / and **refreshments** / in the cafeteria / after this ceremony. // Please join me / in a **round of applause**.`, tips: ['retirement [ritáiərmənt]', 'operations [àpəréiʃənz]', 'applause [əplɔ́ːz]'] },
  { id: 'p1-36', cat: 'tour', topic: '시티 투어 버스', g: `Welcome aboard / the **Downtown City Tour**. // For the next **ninety minutes**, / we will travel through the **old town**↗, / the **harbor**↗, / and the **central market**↘. // Please **remain seated** / while the bus is moving. // You will have **twenty minutes** / at the **harbor** / to take photos / and enjoy the view. // If you have any questions, / please ask your **guide**. // **Restrooms** are located / at the back of the bus, / and **bottled water** / is available for free. // The bus will leave the harbor / at **two thirty** sharp, / so please be **on time**.`, tips: ['ninety(90) vs nineteen(19)', 'harbor [hɑ́ːrbər]', 'remain seated 또박또박'] },
  { id: 'p1-37', cat: 'voice', topic: '택배 지연 음성 메시지', g: `Hello, / this is **Lisa** / from **Fast Track Delivery**. // I'm calling about your **package**, / which was supposed to arrive **today**. // Unfortunately, / there was a **delay** / because of **heavy snow**. // Your package will now arrive / **tomorrow** / between **ten** and **twelve**. // If you will not be home, / you can leave it with a **neighbor**↗ / or pick it up / at our **local office**↘. // You can also **track** your package / on our **website**. // If you have any questions, / please call our **customer center** / from **nine** to **six**. // Thank you / for your **patience**.`, tips: ['Unfortunately [ʌnfɔ́ːrtʃənətli]', 'A or B: A↗ or B↘', 'patience [péiʃəns]'] },
  { id: 'p1-38', cat: 'voice', topic: '식당 예약 확인 음성 메시지', g: `Hi, / **Mr. Adams**. // This is **Nancy** / from **Harbor View Restaurant**. // I'm calling to **confirm** your reservation / for **Friday** evening / at **seven thirty**. // We have reserved a **table for six** / near the **window**. // Please note / that we can hold your table / for only **fifteen minutes**, / so please **arrive on time**. // If you want to make any **changes**↗ / or **cancel**↘, / please call us / before **noon** on Friday. // Also, / our **parking lot** is free / for all guests / in the evening. // We look forward / to serving you.`, tips: ['confirm [kənfɝ́ːm] 강세 둘째 음절', 'fifteen(15) vs fifty(50)', 'reservation [rèzərvéiʃən]'] },
  { id: 'p1-39', cat: 'ad', topic: '여행사 광고', g: `Are you dreaming of a **relaxing vacation**? // Then come to **Blue Wave Travel**! // This spring, / we are offering **special packages** / to **Hawaii**↗, / **Bali**↗, / and **Phuket**↘. // Every package includes / **round-trip flights**, / a **five-star hotel**, / and a **free airport shuttle**. // Book **before April first** / and get **twenty percent off**! // Our friendly travel experts / are ready to help you / plan every **detail**, / from **tours** to **restaurants**. // Visit our website / or call us today. // Your **dream vacation** / is only a click away!`, tips: ['Hawaii [həwáii]', 'Phuket [pùːkét] 푸껫', 'round-trip 한 단어처럼'] }
];
